### ISSUE TITLE
Skip the user login page when OIDC is used

### ISSUE THREAD

**Issue by bsctl** [kubeapps/kubeapps#2109] opened 2020-10-13 08:28 UTC
**Question/Feature request**
Is there any way to skip the user login page when OIDC login is enabled? We're integrating kubeapp start link in another dashboard and the user is already logged via OIDC in the parent dashboard. Something similar to Harbor https://github.com/goharbor/harbor/pull/9311

**Comment by andresmgot** [comment] 2020-10-13 09:09
Kubeapps will automatically skip the login page if the user is already authenticated (you can verify so accessing the `/login` page twice after a successful authentication). The only thing that Kubeapps does is trying to obtain cluster resources ([ref](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/Auth.ts#L103)).

The problem is, as far as I know, the domain with which you login using OIDC. You will need to configure either the instance of `oauth2_proxy` that gets deployed with Kubeapps or your existing auth proxy. I have never done something similar so I am afraid there is not much else I can help you with.

Maybe @absoludity can give you further hints.

**Comment by bsctl** [comment] 2020-10-13 11:18
@andresmgot @absoludity thanks for your support. 

> Kubeapps will automatically skip the login page if the user is already authenticated (you can verify so accessing the /login page twice after a successful authentication). The only thing that Kubeapps does is trying to obtain cluster resources (ref).

Yep it works when you access the login page once you already logged in with Kubeapps. It does not when you already logged in with another app (same browser session). We fixed by pointing the parent dashboard directly to the `oauthLoginURI`, i.e. `kubeapps.example.com/oauth2/start`.

Wonder to know if it makes sense to have an option to tell Kubeapps to redirect the root URL 
 `kubeapps.example.com` to the OIDC login URI `kubeapps.example.com/oauth2/start` . Thanks

**Comment by andresmgot** [comment] 2020-10-13 12:50
Indeed, since you are using an external OIDC proxy, you need to change the `oauthLoginURI` and `oauthLogoutURI`. Also, you will want to remove the authProxy that is deployed along with kubeapps setting `authProxy.external` to `true`.

> Wonder to know if it makes sense to have an option to tell Kubeapps to redirect the root URL
> `kubeapps.example.com` to the OIDC login URI `kubeapps.example.com/oauth2/start` . Thanks

It does so when the auth proxy is enabled (and as far as I understand it's working like that for you). Or do you mean to have a different URL?

Let me close this issue if you managed to have it working, re-open it if you are still finding issues.

**Comment by andresmgot** [comment] 2020-10-13 14:20
Ah, I understood otherwise. It's not clear to me then if you were able to skip the second login. (I understand so from your message "We fixed by pointing the parent dashboard directly to the oauthLoginURI, i.e. kubeapps.example.com/oauth2/start.")

> My question was about to introduce an option to force redirect from the root URL
> `kubeapps.example.com to` the OIDC login `URI kubeapps.example.com/oauth2/start`.

That's something doable, WDYT @absoludity?

**Comment by absoludity** [comment] 2020-10-20 01:28
Yep, we only have the root URL showing the login button so it was consistent with the token auth. +1 to skip it by default (I never liked the message "Your administrator has configured etc. , so click here"

**Closed** 2020-11-09 09:58 UTC
