### ISSUE TITLE
Multiple deploy issues using kubeapps

### ISSUE THREAD

**Issue by anannaya** [kubeapps/kubeapps#505] opened 2018-08-17 10:16 UTC
**Issue1:** : When i do delete of the deployed application ,dependent chart is not getting deleted.
 I tried the same using helm command which is deleting 
$ helm install --name my-release stable/wordpress
$ helm delete my-release
 Why kubeapps does not ? 

**Issue2** : How do i upgrade the only the dependent chart:
 I have a application   full-app   ---->  x
                                   full-app   ----> y

If there is any issues , I would like to upgrade only the ( y or x). Is there any way i can upgrade only those using helm not kubectl.

**Comment by andresmgot** [comment] 2018-08-17 15:45
Hi @anannaya,

Regarding your first issue, I am not able to reproduce it. I've installed the `stable/wordpress` chart that depends on the `mysql` chart and both using the `helm` cli and Kubeapps I am able to delete the release and the resources related to `mysql`. Why do you say that the dependent chart is not deleted? What resources remain there?

Regarding the second issue you can clone the `charts` repository (https://github.com/helm/charts). You will find the dependencies of a chart in the file `./stable/<app>/requirements.yaml`. If you update the versions there and execute `helm dep up ./stable/<app>` it will update the file `requirements.lock`  with the new versions. Then if you want to upgrade your running app without upgrading the main version you can execute `helm upgrade --name <your_app_name> --version <your_app_version> ./stable/<app>`. 

If you have more doubts about how to work with upgrades you can check the `helm` docs: https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md

**Comment by anannaya** [comment] 2018-08-17 17:02
Issue1:
I am using the Kubeapps Installer version: v1.0.0-alpha.5,
Sorry for the confusion , the problem looks like with 2.1.10 with mariadb.
bitnami/wordpress	2.1.10       	4.9.8         	Web publishing platform for building blogs and ...

Issue2: Thanks for explanation, actually i am aware of this procedure. Is there any similar way in kubeapps?   Like i want to upgrade the dependent charts because In my application kubeapps does not shows whats dependent charts it is installed. Please correct my understanding.

**Comment by anannaya** [comment] 2018-08-20 04:49
@prydonius Is there any way to handle dependencies using kubeapps?

**Comment by prydonius** [comment] 2018-08-22 20:35
@anannaya unfortunately right not it's not possible, but it's a good feature idea. The one thing that makes this difficult is that AFAIK the Tiller state isn't aware of dependencies and we'd need to look at the chart itself to see what dependencies there are.

Also, since dependencies are embedded in the parent chart and charts are immutable packages, we can't really control the version of the dependency at the time of deployment. This is probably something that should be handled out-of-bound of Kubeapps (e.g. using the method @andresmgot suggests above).

**Comment by prydonius** [comment] 2018-08-23 19:32
@anannaya I created https://github.com/kubeapps/kubeapps/issues/529 to capture your request. Closing this out, thanks!

**Closed by prydonius** 2018-08-23 19:32 UTC
