### ISSUE TITLE
Multiple kubeapps on single cluster cannot distinguish each others global and local app repos

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1923] opened 2020-08-05 08:45 UTC
### Description:

Having two kubeapps installations interfere with each other AppRepositories.
See:  https://kubernetes.slack.com/archives/C9D3TSUG4/p1596549628152100

### Steps to reproduce the issue:

1. create a ns1, install kubeapps into it, defining an initial repo: https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L226
2. create a ns2, install kubeapps into it, defining an initial repo as in 1, set helm3=true
3. Observe that the catalog of charts is there, but when you click an app to upgrade it it will fail because it cannot find the chart.
4. k -n ns1 get cronjobs will show TWO cronjobs, despite there is only one repo added for this installation, i.e. it discovers the apprepo defined in both ns1 and ns2 - same for the other install.

# Fix
If I manually delete the extraneous jobs it works again.

### Version of Helm, Kubeapps and Kubernetes:

I noticed the problem when upgrading from 3.7.1 to 3.7.4 (chart version)

**Comment by absoludity** [comment] 2020-08-05 23:34
Note that it is by design that Kubeapps discovers app repositories in other namespaces by default, but not that you are unable to install.

What I suspect is happening here is that at step 3., the catalog is providing both the item from the installations own repository as well as that from the namespace where the other installation is but is hiding the duplicates. One simple fix on Kubeapps side may be to prefer global app repo charts (when displaying the catalog for all namespaces).

We'll reproduce, investigate and fix.

**Comment by davidkarlsen** [comment] 2020-08-19 07:27
Were you able to reproduce? It seems the cronjob is created when you recreate the pods in the kubeapps namespace.

**Comment by absoludity** [comment] 2020-08-19 07:33
Sorry David, I've been flat-out working to release the multi-cluster work (hence moving this to the backlog for this iteration), but am keen to reproduce and investigate once that's done.

**Comment by absoludity** [comment] 2020-09-21 04:27
Hi David. I took some time today to try to reproduce this (but note that there have been quite a few changes since you last tested). What I found was:

* As expected (see above), after installing the second Kubeapps (kubeapps2) I see an additional sync job in my original namespace, as the AppRepository for the new installation is just a namespaced repository in the original application:
```
k -n kubeapps get po
NAME                                                        READY   STATUS      RESTARTS   AGE
apprepo-kubeapps-sync-bitnami-1600661400-w4dj5              0/1     Completed   0          7m23s
apprepo-kubeapps-sync-bitnami-tw5s8-7g6g7                   0/1     Completed   1          12m
apprepo-kubeapps2-sync-bitnami-6nxrk-m6q9g                  1/1     Running     0          30s
```

* Unlike your experience, I'm able to deploy (eg, I tested apache) from either my default namespace (which uses the global repository), or the `kubeapps2` namespace (which uses the repo/chart from that namespace) without issue.

In my case, I didn't install a version running tiller-proxy etc., just two helm3 installs.

On that note, we're preparing to remove the tiller-proxy support in the Kubeapps 2.0 pre-release later this week (see #2044). We haven't yet decided whether we'll need to continue supporting a Kubeapps 1.x with the tiller support - it depends on the needs of people like yourself (I'm not sure of anyone else still using the tiller support in production clusters, but there could be more). So let us know what your plans are and we'll do our best to ensure a smooth transition. Thanks

**Comment by davidkarlsen** [comment] 2020-09-23 12:19
Hm, not sure what happened (but in the mean time I have upgraded both installs to latest kubeapps) - but now the charts in the repo eventually appear, although with some delay.
Our current plan is to migrate what's possible to helm3, and at the very least do any new workloads directly on helm3.

Some helm2 installs are not so easy to move due to the conversion util `2to3` not working super-smoothly, and re-install is not an option when a chart uses CRDs because uninstalling would remove all the resources too.

But it's a bit unfortunate with the double up cronjob, maybe some filtering could be done based on labels (to tie a given apprepo to a given kubeapps install) - or is that maybe a bit too complex?

**Comment by absoludity** [comment] 2020-09-24 00:19
> Our current plan is to migrate what's possible to helm3, and at the very least do any new workloads directly on helm3.

How will you stop people using your kubeapps-with-tiller-proxy version from installing new things? (I guess you could modify the service account used by tiller-proxy). I don't know any other details about your env, but it'd seem a better discouragement (while still being usable) to limit interactions with the existing helm2 deployments to the `helm` CLI, and just run one instance of Kubeapps for all new workloads etc. (but maybe that's my own bias :) ).

> But it's a bit unfortunate with the double up cronjob, maybe some filtering could be done based on labels (to tie a given apprepo to a given kubeapps install) - or is that maybe a bit too complex?

No, that'd be simple enough I think. An app repository added to the kubeapps' installation namespace could receive a specific label with a value identifying the kubeapps namespace. The app repository controller could ignore any app repos that are identified as global but the value doesn't match its kubeapps namespace.

Still, it's a short-term solution to a short-term problem.

**Comment by andresmgot** [comment] 2020-09-29 15:27
If I understood this issue, the problem is that kubeapps in `ns2` is detecting app repositories in `ns1` while that should be the job only for the kubeapps instance in `ns1`, right?

The issue is easy to fix from the `apprepository-controller` point of view. We could configure it to listen for apprepositories in a namespace only. The problem for that is that anything would be preventing users from creating app repositories in other namespaces (lets say `ns3`). For that we would need to deploy Kubeapps in "namespace" mode, not allowing people to change the namespace they are (removing the Context Selector). WDYT?

**Comment by absoludity** [comment] 2020-09-30 05:37
> If I understood this issue, the problem is that kubeapps in `ns2` is detecting app repositories in `ns1` while that should be the job only for the kubeapps instance in `ns1`, right?

Yep.

> The issue is easy to fix from the `apprepository-controller` point of view. We could configure it to listen for apprepositories in a namespace only.

Yes, though that is a step in the opposite direction that we want to head (ie. Kubeapps deploying charts from app repos on multiple clusters) for a short-term problem which David has. That said, I'm happy to enable it as a manual switch (rather than a chart option) which David can use until he no longer needs to run the tiller-proxy version on the same cluster. See #2084 (we still have the binary argument available, it just wasn't used).

> The problem for that is that anything would be preventing users from creating app repositories in other namespaces (lets say `ns3`). For that we would need to deploy Kubeapps in "namespace" mode, not allowing people to change the namespace they are (removing the Context Selector). WDYT?

I'm -1 on any public functionality of the chart / Kubeapps here, given it's a short-term problem (needing to run two kubeapps instances in the same cluster) unless we do so properly (ie. labelling app repos as mentioned above) so that it works consistently without requiring a "namespace" mode.

**Comment by andresmgot** [comment] 2020-09-30 08:54
> I'm -1 on any public functionality of the chart / Kubeapps here, given it's a short-term problem (needing to run two kubeapps instances in the same cluster) unless we do so properly (ie. labelling app repos as mentioned above) so that it works consistently without requiring a "namespace" mode.

I am not talking to do that for the short-term problem here. I'm thinking in the use case in which a user wants to use Kubeapps in a cluster in which they only have access to a single namespace and still be able to create different app repositories.

**Closed** 2020-09-30 22:14 UTC

**Comment by absoludity** [comment] 2020-10-01 23:28
> I am not talking to do that for the short-term problem here. I'm thinking in the use case in which a user wants to use Kubeapps in a cluster in which they only have access to a single namespace and still be able to create different app repositories.

That use-case is already supported (in that you can use Kubeapps and create app repos in the one namespace to which you have access etc.), but from our conversation, I think you specifically mean that they can have kubeapps installed in their one namespace, while other users have Kubeapps installed in their other namespace, each with its own global repositories. Which is the same use-case that the labelling strategy would apply to, without requiring a "namespace" mode or similar, I think?

**Comment by andresmgot** [comment] 2020-10-05 08:34
> > I am not talking to do that for the short-term problem here. I'm thinking in the use case in which a user wants to use Kubeapps in a cluster in which they only have access to a single namespace and still be able to create different app repositories.
> 
> That use-case is already supported (in that you can use Kubeapps and create app repos in the one namespace to which you have access etc.), but from our conversation, I think you specifically mean that they can have kubeapps installed in their one namespace, while other users have Kubeapps installed in their other namespace, each with its own global repositories. Which is the same use-case that the labelling strategy would apply to, without requiring a "namespace" mode or similar, I think?

Yes but the labelling would not be required (IMO) as far as the controller only listens in their installation namespace and namespaced repositories are not allowed in that "mode".
