### ISSUE TITLE
Failed to set CA of helm repo

### ISSUE THREAD

**Issue by zkyle95** [kubeapps/kubeapps#2197] opened 2020-12-02 02:56 UTC
### Description:

I'm using kubeapps behind a proxy, and the CA of proxy server is self-signed. So i tried to set the proxy CA for bitnami repo, but failed and got log **"Failed to append /usr/local/share/ca-certificates/ca.crt to RootCAs"** from pod `apprepo-kubeapps-sync-bitnami`

### Steps to reproduce the issue:

1. Open page **Application Repository**
2. Edit repo **bitnami**
3. Filled **Custom CA Certificate (optional)** with my proxy CA
4. Click **Update Repo**

### Describe the results you received:

![image](https://user-images.githubusercontent.com/70498728/100821702-e448b200-348b-11eb-9b5d-c0141eb1db3e.png)

### Describe the results you expected:

CA be trusted

### Additional information you deem important (e.g. issue happens only occasionally):

```bash
$ kc logs apprepo-kubeapps-sync-bitnami-1606876200-8t2s8 -nkubeapps
time="2020-12-02T02:30:15Z" level=fatal msg="Failed to append /usr/local/share/ca-certificates/ca.crt to RootCAs"
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2020-12-02 10:23:10.256962283 +0800 CST deployed        kubeapps-5.0.0  2.0.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment] 2020-12-02 05:42
Hi @zkyle95 , thanks for the details in the report. Looking at where we raise that error, it's if the `AppendCertsFromPEM` function returns false, which according to the [docs of `AppendCertsFromPEM`](https://golang.org/pkg/crypto/x509/#CertPool.AppendCertsFromPEM) happens if it cannot parse any certs from the provided data. So the first thing I'd check is that you're pasting a correct CA cert. It should start with `-----BEGIN CERTIFICATE-----` and end with `-----END CERTIFICATE-----` as the form shows. So that's the error fro the logs, but that's not the only error.

Even if you fix that, I suspect the sync job will still fail to reach bitnami.com, unless you're also specifying the https_proxy env vars in the sync job template. I think you'll find the exact scenario is described with a solution in #2139 . I'll close this as a duplicate of that issue, but please re-open if you think it's different.

Duplicate of #2139

**Closed by absoludity** 2020-12-02 05:42 UTC
