### ISSUE TITLE
Support for deploying to multiple k8 clusters

### ISSUE THREAD

**Issue by pocha** [kubeapps/kubeapps#1711] opened 2020-05-02 18:21 UTC
My team at Locus.sh is setting up Kubeapps to deploy to two of our clusters - one in Aliyun cloud & another in GCP. To make it easier for our devs to deploy, so that they don't have to go to two different dashboards, we are thinking of tweaking the Kubeapps codebase to have provision to choose the cluster during login. 

Do you guys think this is something that you would be happy to review & also take it as contribution to this project ?

**Comment by absoludity** [comment] 2020-05-03 23:17
Hi there @pocha . Multi-cluster support is our first priority for this quarter. We are planning to work on the design over the next weeks and would be keen to work together in some form with others in the community who need this (there have been quite a few queries about it).

I'll try to make sure we put up our general direction in the next week or two (a proposal in the repo), followed by a more detailed design doc later on, so we can start gathering concerns and finding out who can contribute and how :) Let me know if that suits you (or not!) or whether you have other constraints for the timeline or implementation etc.

**Comment by pocha** [comment] 2020-05-04 04:59
Hi @absoludity, thanks for quick response. Our dev Akhil, has already raised a PR internally as we speak. I can ask Akhil to send it formally upstream for you folks to review.

We would be happy to tweak it the right way. If it seems to require a major rework, we can deploy it locally for Locus while continue to work on the refactor.

<off-topic> Akhil has done a few other things as well which are generic in nature. One of it is to replace the select dropdown for selecting version with a table, which is conducive when you have large number of versions per chart or releases. We were also thinking of sending those changes for your review</off-topic>

**Comment by absoludity** [comment] 2020-05-07 03:56
Also off-topic: @pocha wondering if you might be open to telling us a bit about how you're using / planning to use Kubeapps? We're trying to collect use cases and stories from people to also help future planning etc. If you're open to that, I can setup a call, or email exchange or whatever (I've followed you on twitter, so you can msg me there). Thanks either way.

**Comment by absoludity** [comment] 2020-05-20 04:45
I've outlined an approach for discussion at https://github.com/kubeapps/kubeapps/pull/1746 (and linked from there) which doesn't necessarily meet your specific needs (more below) but aims to be a compromise between what's feasible, existing k8s support (ie. multi-cluster auth with OIDC), and security. Regarding the approach you outlined:

> we are thinking of tweaking the Kubeapps codebase to have provision to choose the cluster during login.

Choosing a cluster during login could work as long as the Kubeapps pods can reach the API server of the additional cluster (which is also one of the assumptions I've outlined there), but it'd need to be choosing from a list of options preconfigured by the admin installing kubeapps (otherwise kubeapps would need to proxy to any endpoint, which would be dangerous). I've included this as a possible alternative under the [UX Cluster selector heading](https://docs.google.com/document/d/1-6cKxOsW6K5u3lK7Om2zQeVYVPxzHT6dVwej5wy3_9A/edit?ts=5ebe6284#heading=h.ht9nbsecyhbg). Feel free to add thoughts and comments there.

**Comment by locus-akhilkrishna** [comment] 2020-05-21 07:29
@absoludity thanks for notifying us, we also did the same change as you mentioned by compromising OIDC support, we added an option to choose which stack a user wants to log in on the login page itself and the provide an appropriate token for the respective stack. Admin has to preconfigure the kubeapps installation by providing the Kubernetes endpoint and CA certificate. Also, we changed the direct Kubernetes API call from the frontend by proxying the request via kubeops.

Also, we felt a feature to be missing because on the default Kubernetes stack, the user with privilege on kubeapps namespace can manage the app repository but login with other Kubernetes stack token won't able to manage app repositories. So probably some sort of flexibility would be really helpful going forward as many people would find this use case important to manage multiple Kubernetes stacks via single kubeapps.

I can raise PR for what we did and internally we are using the updated kubeapps, but the version using is 1.8.2. 

Also, I have a suggestion instead of Kubernetes handling the authentication and RBAC, why can't the Kubeapps handle it so that for the multiple clusters we don't have to compromise features like SSO or security. So we will have a token for each cluster which will authenticate with Kubernetes as Kubeapps on behalf of the users.

**Comment by absoludity** [comment] 2020-05-22 00:03
Thanks for the details @locus-akhilkrishna 

> @absoludity thanks for notifying us, we also did the same change as you mentioned by compromising OIDC support, we added an option to choose which stack a user wants to log in on the login page itself and the provide an appropriate token for the respective stack.

Yes, that sounds quite similar - the only difference is that I'd prefer to allow people to switch clusters without re-logging in (if the clusters use the same OIDC endpoint). But perhaps selection at login is a good starting point, while switching clusters after login only available if configured. I've noted this in the doc.

> Admin has to preconfigure the kubeapps installation by providing the Kubernetes endpoint and CA certificate. Also, we changed the direct Kubernetes API call from the frontend by proxying the request via kubeops.

It's always proxied by kubeops? Perhaps you mean that you additionally proxied the other clusters too (in which case, yep, that makes sense).

> 
> Also, we felt a feature to be missing because on the default Kubernetes stack, the user with privilege on kubeapps namespace can manage the app repository but login with other Kubernetes stack token won't able to manage app repositories. So probably some sort of flexibility would be really helpful going forward as many people would find this use case important to manage multiple Kubernetes stacks via single kubeapps.

Oh this is possible now, it's just because it's an explicit role that you need to associate with the user (or service-token). You mentioned you've done these changes against 1.8.2 for which the [access-control for AppRepositories is documented here](https://github.com/kubeapps/kubeapps/blob/v1.8.2/docs/user/access-control.md#app-repositories). (It changed in 1.10, but that's not relevant to you).

> 
> I can raise PR for what we did and internally we are using the updated kubeapps, but the version using is 1.8.2.

If you get a chance, that'd be interesting to see (you may need to push a 1.8.2 branch to your repo to target so the diff will be just the relevant changes, as we don't have release branches, only tagged).

> 
> Also, I have a suggestion instead of Kubernetes handling the authentication and RBAC, why can't the Kubeapps handle it so that for the multiple clusters we don't have to compromise features like SSO or security.

So a couple of things here: we absolutely should not have to "compromise" on SSO or security - that wasn't what I meant above (I meant that I was compromising by not enabling the service-account token authz, mainly because I don't want to encourage people using it due to security concerns. We can still choose to support service-token authz, but service account tokens are not intended for user-auth, and for good reason). Utilising the K8s API servers support of external IdPs is the ideal, in my opinion - as there is one trusted source (the IdP) for authentication which is used both in Kubeapps and for operations on the cluster via Kubeapps.

Kubeapps has been from the start a been a light wrapper around Kubernetes (and Helm). We could at some point later actually build a separate authz layer, independent of K8s RBAC, but it would need to be worth-while - there are a lot of extra costs (in particular, Kubeapps would need to map its auth model to k8s RBAC, requiring a basis of a high-privileged account, which is exactly what Tiller used to be in Helm 2 - and it was removed for good reason :) ).

> So we will have a token for each cluster which will authenticate with Kubernetes as Kubeapps on behalf of the users.

Exactly, there is a lot of effort needed to ensure that this (high-privileged by design) token cannot be misused (let alone secured etc.). Again, this is how tiller operated.

Thanks for all your input and thoughts!

**Comment by absoludity** [comment] 2020-05-26 07:00
I'm going to mark this as a duplicate of an issue I've just created to manage the implementation - hope that's ok. I think I've captured all the useful info into the design proposal for now. Let me know if you disagree.

Duplicate of #1753

**Closed by absoludity** 2020-05-26 07:00 UTC

**Comment by absoludity** [comment] 2020-05-26 07:01
Duplicate of #1753

**Comment by locus-akhilkrishna** [comment] 2020-06-03 05:46
@absoludity can you please help me on creating a branch for 1.8.2, so that I can create a PR with the base branch as 1.8.2

**Comment by andresmgot** [comment] 2020-06-03 08:45
not sure if this is what you are asking but when creating a PR, you can select to use a tag as the base:
![Screenshot from 2020-06-03 10-44-03](https://user-images.githubusercontent.com/4025665/83615797-50069c80-a587-11ea-9fd4-623619444b73.png)

**Comment by locus-akhilkrishna** [comment] 2020-06-03 14:22
With tag as a base we cannot create PR, have to create a branch from the tag.

**Comment by absoludity** [comment] 2020-06-04 01:26
Yeah - only diffs against tags, no PR. I've created a 1.8.2 branch that you can use as a base, but note that you can also create that in your own github kubeapps repo and generate a PR against that. Or just use a link to the diff against the tag. But fine either way.

As above, we're starting the multi-cluster work now and working against master and won't be merging/maintaining any patches on 1.8.2, but it'll still be useful to see where ideas matched or where we can learn from each others ideas :) Thanks!
