### ISSUE TITLE
charts are not updated after adding local hem repo.

### ISSUE THREAD

**Issue by anannaya** [kubeapps/kubeapps#326] opened 2018-05-23 11:41 UTC
Hi,

Below are the error i am seeing on apprepository-controller pod.

{{
I0523 08:45:25.091142       1 controller.go:234] Successfully synced 'kubeapps/imshelm'
I0523 08:45:25.091183       1 event.go:218] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"imshelm", UID:"c7ff0564-5e5d-11e8-afbf-fa163e77c7e6", APIVersion:"kubeapps.com", ResourceVersion:"5652781", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
E0523 08:45:25.092064       1 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"imshelm.1531366a08b9df50", GenerateName:"", Namespace:"kubeapps", SelfLink:"", UID:"", ResourceVersion:"5647638", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"imshelm", UID:"c7ff0564-5e5d-11e8-afbf-fa163e77c7e6", APIVersion:"kubeapps.com", ResourceVersion:"5652781", FieldPath:""}, Reason:"Synced", Message:"AppRepository synced successfully", Source:v1.EventSource{Component:"apprepository-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63662658377, loc:(*time.Location)(0x189fb60)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbeb96869456e8d5f, ext:81718114346573, loc:(*time.Location)(0x189fb60)}}, Count:3, Type:"Normal"}': 'events "imshelm.1531366a08b9df50" is forbidden: User "system:serviceaccount:kubeapps:apprepository-controller" cannot patch events in the namespace "kubeapps"' (will not retry!)
}}

Br,
Anand

**Comment by anannaya** [comment] 2018-05-23 11:51
![image](https://user-images.githubusercontent.com/19487932/40422653-a550ce68-5ead-11e8-9a47-90f938bdea36.png)

**Comment by prydonius** [comment] 2018-05-29 22:03
@anannaya sorry for the delayed response. What version of Kubeapps are you seeing this on? Also, can you see if there are any CronJobs/Jobs created for your repository sync? You should be able to see the pods with `kubectl get po --show-all -n kubeapps`.

**Comment by anannaya** [comment] 2018-05-30 04:29
[root@os-kubeserver1 ~]# kubeapps version
Kubeapps Installer version: v1.0.0-alpha.3

[root@os-kubeserver1 ~]# kubectl get po --show-all -n kubeapps
NAME                                        READY     STATUS      RESTARTS   AGE
apprepo-cleanup-imshelm-d4m7v-g9zd4         0/1       Completed   0          6d
apprepo-cleanup-imshelm-knb8x-zg87k         0/1       Completed   0          6d
apprepo-cleanup-imshelm-snzbk-ldw9m         0/1       Completed   0          6d
apprepo-cleanup-imslocalhelm-t7w2z-vq9kt    0/1       Completed   0          6d
apprepo-cleanup-incubator-n5b4v-4q5s6       0/1       Completed   0          6d
apprepo-sync-imshelm-1527076800-95vvb       0/1       Completed   0          6d
apprepo-sync-imshelm-1527080400-k4vl6       0/1       Completed   0          6d
apprepo-sync-imshelm-1527084000-qmz9d       0/1       Completed   0          6d
apprepo-sync-imshelm-1527141600-5qnzc       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-crzpx       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-gdk42       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-nzdrd       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-rjs7v       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-tb86q       0/1       Error       0          5d
apprepo-sync-imshelm-1527141600-tmx4l       0/1       Error       0          5d
apprepo-sync-imshelm-1527145200-rnxs7       1/1       Running     0          5d
apprepo-sync-imshelm-2mslg-rsjgf            0/1       Completed   0          6d
apprepo-sync-imshelm-qt96s-js9lb            0/1       Completed   0          6d
apprepo-sync-imshelm-trmqc-8lm4m            0/1       Completed   0          6d
apprepo-sync-imshelm-wz8s4-69mcb            0/1       Completed   0          6d
apprepository-controller-584b4b54d5-tzd8z   1/1       Running     0          7d
chartsvc-d5f86ddf5-822pm                    1/1       Running     0          7d
kubeapps-5bdd68c5cc-5rh75                   1/1       Running     0          7d
kubeapps-dashboard-ui-567b67844-pqtmv       1/1       Running     0          7d
mongodb-65bb4ccf77-2tfpp                    1/1       Running     0          7d
tiller-deploy-544497fcfc-ckj2t              2/2       Running     0          7d

**Comment by prydonius** [comment] 2018-05-30 22:11
Please add the `--show-all` flag to the above command to see completed jobs. It looks like one of the sync jobs (`apprepo-sync-imshelm-1527145200-rnxs7`) has been running for 5 days though. Can you check to see if there are any logs for that?

`kubectl logs -n kubeapps apprepo-sync-imshelm-1527145200-rnxs7`

**Comment by anannaya** [comment] 2018-05-31 04:51
Hi,
[root@os-kubeserver1 ~]# kubectl get po --show-all -n kubeapps
NAME                                        READY     STATUS      RESTARTS   AGE
apprepo-sync-imshelm-1527145200-rnxs7       1/1       Running     0          6d
apprepo-sync-imshelm-qwrw7-r5mpn            0/1       Completed   0          3m
apprepo-sync-imshelm-rd7q6-2v4zk            0/1       Completed   0          4m
apprepository-controller-584b4b54d5-tzd8z   1/1       Running     0          8d
chartsvc-d5f86ddf5-822pm                    1/1       Running     0          8d
kubeapps-5bdd68c5cc-5rh75                   1/1       Running     0          8d
kubeapps-dashboard-ui-567b67844-pqtmv       1/1       Running     0          8d
mongodb-65bb4ccf77-2tfpp                    1/1       Running     0          8d
tiller-deploy-544497fcfc-ckj2t              2/2       Running     0          8d


[root@os-kubeserver1 ~]# kubectl logs -n kubeapps apprepo-sync-imshelm-qwrw7-r5mpn
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=feef
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=pcscf
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=feeg
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=scscf
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=cmrelay
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=eatf
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=ibcf
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=icscf
time="2018-05-31T04:43:01Z" level=info msg="icon not found" name=dispatcher
time="2018-05-31T04:43:01Z" level=info msg="Successfully added the chart repository imshelm to database"

Br,
Anand

**Comment by anannaya** [comment] 2018-05-31 04:56
One more clue: I have tried same version of kubeapps  on my laptop minikube. It worked.
I am facing this probelm only on lab machine.. I have added the NAT rules to open the kubeapps GUI from outside .. I think that should not create any probelm.

**Comment by prydonius** [comment] 2018-05-31 21:33
Thanks for the info @anannaya.

Couple of things:

1. Any logs from the pod that seems to be stuck running? (apprepo-sync-imshelm-1527145200-rnxs7)? If not, could you try killing it?
2. How exactly are you connecting to the Kubeapps UI?
3. Please paste the output of `kubectl exec -ti -n kubeapps-dashboard-ui-567b67844-pqtmv curl http://chartsvc:8080/v1/charts`

**Comment by anannaya** [comment] 2018-06-01 05:27
[root@os-kubeserver1 ~]# kubectl exec -ti -n kubeapps  kubeapps-dashboard-ui-567b67844-pqtmv curl http://chartsvc:8080/v1/charts
curl: (7) Failed to connect to chartsvc port 8080: Connection refused
command terminated with exit code 7
[root@os-kubeserver1 ~]#

**Comment by sameersbn** [comment] 2018-06-01 06:31
>  curl: (7) Failed to connect to chartsvc port 8080: Connection refused

This does not seem right. What's the output of

```bash
kubectl -n kubeapps get svc
```

```bash
kubectl -n kubeapps logs chartsvc-d5f86ddf5-822pm
```

btw, does removing the local helm repo from kubeapps change anything? Are you able to sync charts from the stable repo?

**Comment by anannaya** [comment] 2018-06-01 06:38
[root@os-kubeserver1 ~]# kubectl -n kubeapps get svc
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
chartsvc                ClusterIP   10.100.178.95    <none>        8080/TCP    9d
kubeapps                ClusterIP   10.104.160.195   <none>        8080/TCP    9d
kubeapps-dashboard-ui   ClusterIP   10.97.162.159    <none>        8080/TCP    9d
mongodb                 ClusterIP   10.99.229.171    <none>        27017/TCP   9d
[root@os-kubeserver1 ~]# kubectl -n kubeapps logs chartsvc-d5f86ddf5-822pm
[root@os-kubeserver1 ~]#

**Comment by sameersbn** [comment] 2018-06-01 07:18
> [root@os-kubeserver1 ~]# kubectl -n kubeapps logs chartsvc-d5f86ddf5-822pm

I think this is where the problem is, the `chartsvc` daemon does not appear to ready. Typically a log message such as `time="2018-05-30T09:59:04Z" level=info msg="Started RateSvc" addr=":8080"` is expected as the first log line.

We should first check if a connection to the mongodb server can be established, 

```bash
$ get the mongo root password (required for authentication in the next step)
kubectl get secrets -n kubeapps mongodb -o jsonpath='{.data.mongodb-root-password}' | base64 --decode

$ create a client container  and attempt a connect
kubectl -n kubeapps run mongo-client --image=bitnami/mongodb:3.4.9-r1 --rm -it  --restart=Never --command -- bash
> mongo --host mongodb.kubeapps -u root -p --authenticationDatabase admin
```

Ideally the client should authenticate with the mongodb server and login successfully.

Additionally could you paste the output of

```bash
kubectl -n kubeapps logs mongodb-65bb4ccf77-2tfpp
```

**Comment by sameersbn** [comment] 2018-06-01 07:18
> ->> How can i configure the kubeapps to work behind proxy to get internet access?

As per my knowledge, such configuration is not current possible.

**Comment by anannaya** [comment] 2018-06-01 09:04
[root@os-kubeserver1 ~]# kubectl get secrets -n kubeapps mongodb -o jsonpath='{.data.mongodb-root-password}' | base64 --decode
ax3zrXmfWKuy8o8i[root@os-kubeserver1 ~]# kubectl -n kubeapps run mongo-client --image=bitnami/mongodb:3.4.9-r1 --rm -it  --restart=Never --command -- bash
If you don't see a command prompt, try pressing enter.
root@mongo-client:/# 
root@mongo-client:/#  mongo --host mongodb.kubeapps -u root -p --authenticationDatabase admin
MongoDB shell version v3.4.9
Enter password: 
connecting to: mongodb://mongodb.kubeapps:27017/
MongoDB server version: 3.4.9
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
Server has startup warnings: 
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] 
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] 
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-05-22T10:07:49.361+0000 I CONTROL  [initandlisten] 



[mango_db_logs.txt](https://github.com/kubeapps/kubeapps/files/2062061/mango_db_logs.txt)

**Comment by prydonius** [comment] 2018-06-01 16:31
It looks like the connection to MongoDB from the Golang library seems to be failing, but connecting from another MongoDB container works fine. I'm not sure the best way to debug what's happening in the Golang connection.

On a related side note, the chartsvc and repo sync containers should crash after a timeout if it can't connect to MongoDB. I remember this was broken before, and then later fixed, but looks like this might have regressed again. We should fix this and that might give us a better idea of what's happening here.

**Comment by anannaya** [comment] 2018-06-02 14:49
How do we fix this?

**Comment by prydonius** [comment] 2018-06-04 21:32
@sameersbn any ideas? I'm not sure how we could debug this...

**Comment by sameersbn** [comment] 2018-06-05 07:11
@prydonius I am not sure how we could debug this,

@anannaya at the moment I can offer the following suggestions that you could try and let us know if anything chages.

1. Delete the chartsvc pod so that its re-created and check the logs if it was able to connect to the mongodb server

```bash
kubectl -n kubeapps delete pod chartsvc-d5f86ddf5-822pm
kubectl -n kubeapps logs -f chartsvc-<XXXXX>
```

If the output has the line `time="XXXXXXX" level=info msg="Started RateSvc" addr=":8080"`, it would indicate that the chart svc is running properly and you could try to perform the sync or test the chartsvc api endpoint as listed in https://github.com/kubeapps/kubeapps/issues/326#issuecomment-393687713

2. Swap out the bitnami/mongodb container with `mongodb:3.6-jessie` (worth a try!)

```bash
kubectl -n kubeapps delete deploy mongodb
kubeapps up --dry-run | \
  sed -e 's|bitnami/mongodb:3.4.*|mongo:3.6-jessie|' \
      -e 's|name: MONGODB_ROOT_PASSWORD|name: MONGO_INITDB_ROOT_USERNAME\n          value: "root"\n        - name: MONGO_INITDB_ROOT_PASSWORD|' \
      -e 's|/bitnami/mongodb|/data/db|' \
  | kubectl apply -f -
```

**Comment by anannaya** [comment] 2018-06-06 05:14
I will try those and update..

**Comment by prydonius** [comment] 2018-07-03 01:05
@anannaya any luck with this?

**Comment by noalphakamp** [comment] 2018-07-10 20:50
I can confirm @sameersbn last suggestion worked for me!! Souce: just newbie to kubernetes trying to fix this for hours.  I tried mongo 4.0, I tried enabling ipv6 like previous closed issues sugested.. only 3.6-jessie seemed to have worked

**Comment by anannaya** [comment] 2018-07-11 04:15
I will try with mongo:3.6-jessie.

**Comment by prydonius** [comment] 2018-07-11 22:46
This should be fixed in the new release without the need for the above workaround. Thanks!

**Comment by anannaya** [comment] 2018-07-12 04:32
@prydonius  Is the issue fixed in Kubeapps v1.0.0-alpha.4 ??  Can i try that?

**Comment by prydonius** [comment] 2018-07-12 17:32
@anannaya it will be in v1.0.0-alpha.5 - sorry for the wait but it should be released soon!

**Comment by arapulido** [comment] 2018-08-08 09:59
@prydonius reminder to close this one when releasing v1.0.0-alpha.5 🔔

**Comment by anannaya** [comment] 2018-08-10 05:25
helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
Error: release kubeapps failed: secrets "kubeapps-mongodb" is forbidden: unable to create new content in namespace kubeapps because it is being terminated.

**Comment by anannaya** [comment] 2018-08-10 05:36
And with 
#kubeapps up
INFO[0000] Fetching schemas for 33 resources            
INFO[0000] Updating customresourcedefinitions apprepositories.kubeapps.com 
INFO[0000] Updating clusterroles apprepository-controller 
INFO[0000]  Creating non-existent clusterroles apprepository-controller 
INFO[0000] Updating clusterrolebindings apprepository-controller 
INFO[0000]  Creating non-existent clusterrolebindings apprepository-controller 
INFO[0000] Updating namespaces kubeapps                 
INFO[0000] Updating clusterroles kubeapps-applications-read 
INFO[0000]  Creating non-existent clusterroles kubeapps-applications-read 
INFO[0000] Updating clusterroles kubeapps-service-catalog-admin 
INFO[0000]  Creating non-existent clusterroles kubeapps-service-catalog-admin 
INFO[0000] Updating clusterroles kubeapps-service-catalog-browse 
INFO[0000]  Creating non-existent clusterroles kubeapps-service-catalog-browse 
INFO[0000] Updating clusterroles kubeapps-service-catalog-read 
INFO[0000]  Creating non-existent clusterroles kubeapps-service-catalog-read 
INFO[0000] Updating clusterroles kubeapps-service-catalog-write 
INFO[0000]  Creating non-existent clusterroles kubeapps-service-catalog-write 
INFO[0001] Updating clusterrolebindings tiller-cluster-admin 
INFO[0001]  Creating non-existent clusterrolebindings tiller-cluster-admin 
INFO[0001] Updating roles kubeapps.apprepository-controller 
INFO[0001]  Creating non-existent roles kubeapps.apprepository-controller 
ERRO[0001] can't install kubeapps components: Error updating roles kubeapps.apprepository-controller: roles.rbac.authorization.k8s.io "apprepository-controller" is forbidden: unable to create new content in namespace kubeapps because it is being terminated. 


Any idea .. I am working behind the proxy with minikube ..Dockec is configured in minikube to understand the proxy environment..

Could you please help me solve this issue?  Either helm or kubeapps is fine for me.

**Comment by andresmgot** [comment] 2018-08-10 08:54
Hi @anannaya, we have pushed a guide for migrating to v1.0.0-alpha.5, have you seen it? It's here: https://github.com/kubeapps/kubeapps/blob/master/docs/user/migrating-to-v1.0.0-alpha.5.md

What's failing for you apparently is that you are trying to reinstall kubeapps while the previous installation has not been cleaned up completely. Give it a couple of minutes between cleaning it up and installing it again. In any case, make sure that `kubectl get pods --all-namespaces -l created-by=kubeapps` doesn't return anything and that the `kubeapps` namespace is empty before trying to install the new version.

If for some reason some resource is blocked and cannot be deleted let us know and we will help you to cleanup that.

**Comment by anannaya** [comment] 2018-08-10 09:15
Hi @andresmgot  
Yes.. I have tried 3hours back.. with v1.0.0-alpha.5.

# kubectl get pods --all-namespaces -l created-by=kubeapps
No resources found.

Could please help me now?

**Comment by anannaya** [comment] 2018-08-10 09:25
$ kubectl get clusterroles
NAME                              AGE
apprepository-controller          3h
kubeapps-applications-read        3h
kubeapps-service-catalog-admin    3h
kubeapps-service-catalog-browse   3h
kubeapps-service-catalog-read     3h
kubeapps-service-catalog-write    3h

**Comment by andresmgot** [comment] 2018-08-10 09:27
It seems that some resources are still there that has not been deleted and prevent the CRD from being fully deleted. Can you execute the following?

```
kubectl get -o  yaml --all-namespaces apprepositories.kubeapps.com
kubectl get -o  yaml --all-namespaces helmreleases.helm.bitnami.com
kubectl get -o  yaml --all-namespaces sealedsecrets.bitnami.com
```

**Comment by andresmgot** [comment] 2018-08-10 09:29
Also please delete those clusterroles

**Comment by anannaya** [comment] 2018-08-10 10:05
Issue is sorted now.. May be some kubenetes cluster issue.
Now the kubeapps is up.
I have added the chartmusium repo as well. But now the bigger problem is GUI console it empty.
http://localhost:43499/charts

kubectl logs deploy/apprepository-controller -n kubeapps
I0810 09:59:26.554123       1 event.go:218] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"nokiahelmrepo", UID:"10b18068-9c84-11e8-b572-080027966c80", APIVersion:"kubeapps.com", ResourceVersion:"431603", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully

kubectl logs deploy/chartsvc -n kubeapps
time="2018-08-10T09:52:18Z" level=info msg="Started chartsvc" addr=":8080"
[negroni] 2018-08-10T09:57:23Z | 200 | 	 27.464634ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T09:57:41Z | 200 | 	 24.376006ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T09:58:24Z | 200 | 	 23.630901ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T09:59:28Z | 200 | 	 13.544553ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T09:59:38Z | 200 | 	 53.898586ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T09:59:47Z | 200 | 	 749.889µs | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:00:00Z | 200 | 	 46.465307ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:01:20Z | 200 | 	 19.273736ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:01:25Z | 200 | 	 683.893µs | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:01:26Z | 200 | 	 2.231725ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:01:27Z | 200 | 	 38.056705ms | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:01:27Z | 200 | 	 896.412µs | chartsvc:8080 | GET /v1/charts 
[negroni] 2018-08-10T10:02:46Z | 200 | 	 18.333025ms | chartsvc:8080 | GET /v1/charts

**Comment by andresmgot** [comment] 2018-08-10 10:12
That should be populated in a short time. If you execute `kubectl get pods -n kubeapps -a` you should see some `apprepo-sync-*` pods, once they are `Completed` the `/charts` view should contain the different charts.

**Comment by arapulido** [comment] 2018-08-10 10:47
Thanks for confirming @anannaya. We will close this issue now. Please, open new ones if you encounter any other issues.

**Closed by arapulido** 2018-08-10 10:47 UTC
Labels: component/chart-repo, kind/question, priority/awaiting-more-evidence

**Comment by anannaya** [comment] 2018-08-11 04:54
Please reopen this issue, There is a strange behaviour with kubeapps.. Its kind of blocker for me.

How to reproduce
1.  Add the chartmusium repo in helm GUI.
2. Then i moved to charts TAB.. Entire GUI is becoming blank..  No error message nothing.

Atleast in v1.0.0-alpha.4 ..There wasnt any GUI issue.. Evnthough charts were not displayed.

Br,
Anand

**Comment by anannaya** [comment] 2018-08-11 05:37
I understood the problem, I deleted all the default helm repos added as part of  kubeapps installation. and i added my local repo.But my repo had some port issue..So kubeapps was not able to sync the charts from repo. i.e i was expecting  charts tab in GUI should show empty.  But the GUI is kind of vanished when i click the charts. 

Thanks for the help anyway.

**Comment by prydonius** [comment] 2018-08-11 21:10
@anannaya thanks for the info, I've filed #470 for this bug.
