### ISSUE TITLE
Launching an app with a name that includes a captialized letter fails

### ISSUE THREAD

**Issue by nomisbeme** [kubeapps/kubeapps#412] opened 2018-07-26 21:09 UTC
I'm running on AKS:
```
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
The alpha4 release installed using the defaults:
```
$ kubectl get po kubeapps-dashboard-ui-8465dc9887-7ssxm -n kubeapps -o jsonpath='{..image}'
kubeapps/dashboard:v1.0.0-alpha.4
```

**Steps to reproduce**
1. Launch kubeapps dashboard in the browser
2. Charts tab > MySQL 5.7.14 > Deploy using Helm
3. Enter a string with a capital letter in the name "Mysql"

**Expected result**
Helm chart is used to create a new release in the cluster

**Actual result**
Sorry! Something went wrong message

**Additional details**
Chrome network tab shows that a post request failed with 422:
```
Request URL: http://localhost:54631/api/kube/apis/helm.bitnami.com/v1/namespaces/default/helmreleases
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 127.0.0.1:54631
Referrer Policy: no-referrer-when-downgrade
```

If capital letters are prohibited this should be handled more gracefully. Better, upper and lower case deployment names should be permitted.

**Comment by prydonius** [comment] 2018-07-26 23:23
Thanks! I think this is a dupe of #318 - moving your comment there.

**Closed by prydonius** 2018-07-26 23:23 UTC

**Comment by nomisbeme** [comment] 2018-07-26 23:30
Thanks, not sure how I missed that issue.
