### ISSUE TITLE
to create token to specific namespace not work. this is the problem

### ISSUE THREAD

**Issue by refaelb** [kubeapps/kubeapps#4040] opened 2022-01-09 08:44 UTC
An error occurred: Unable to create the installed package for the package "bitnami/airflow" using the plugin "helm.packages": rpc error: code = Unauthenticated desc = Missing permissions rpc error: code = Internal desc = Unable to fetch app repo "bitnami" from namespace "kubeapps": unable to get app repository kubeapps/bitnami: apprepositories.kubeapps.com "bitnami" is forbidden: User "system:serviceaccount:default:tokentest" cannot get resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapps"

**Comment by refaelb** [comment] 2022-01-09 08:45
this is the command :

kubectl create -n default serviceaccount tokentest
export KUBEAPPS_NAMESPACE=kubeapps
kubectl create -n kube rolebinding tokentest-kubeapps-applications-write \
  --clusterrole=kubeapps:${KUBEAPPS_NAMESPACE}:apprepositories-write \
  --serviceaccount default:tokentest

**Comment by absoludity** [comment] 2022-01-09 22:42
Hi @refaelb. Can you check whether you actually have the RBAC you think you have, by running the following via kubectl:

```
kubectl --as system:serviceaccount:default:tokentest get apprepositories -n kubeapps
```

The reason I ask is that initially I followed your instructions above and found that your instructions are actually creating the rolebinding in the `kube` namespace, rather than the `kubeapps` namespace (see your previous comment), which means that the service account correctly cannot view apprepositories in the kubeapps namespace.

Let us know.

**Comment by refaelb** [comment] 2022-01-10 14:57
Error from server (Forbidden): apprepositories.kubeapps.com is forbidden: User "system:serviceaccount:default:tokentest" cannot list resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapps"

**Comment by absoludity** [comment] 2022-01-10 22:44
Right, so the error is telling you that the RBAC itself (ie. independent of Kubeapps), does not allow your `tokentest` service account to get app repositories in the `kubeapps` namespace.

> wat i need to do now ? create rbac in kubeapps ns to sa tokentest in deafult ns ??

Currently, yes, if the repository you want your user to access is in the Kubeapps namespace, the user will need RBAC for that (ie. just update your `-n kube` to `-n kubeapps` in your initial statement). Though @castelblanque is working on an issue so that in the future you won't need a special RBAC to view the global app repositories, which will be in a separate namespace. See #3989 for more details.

**Comment by refaelb** [comment] 2022-01-11 08:30
i am sorry i cant token for ns example1   my kubeapps runing in  ns kubeapps how i create token just for example1 ns??

export KUBEAPPS_NAMESPACE=kubeapps
kubectl create -n example rolebinding example-kubeapps-applications-write \
  --clusterrole=kubeapps:${KUBEAPPS_NAMESPACE}:apprepositories-write \
  --serviceaccount default:example

this is create token just for example ns ??

because this is check the err :
An error occurred: Unable to create the installed package for the package "bitnami/airflow" using the plugin "helm.packages": rpc error: code = Unauthenticated desc = Missing permissions rpc error: code = Internal desc = Unable to fetch app repo "bitnami" from namespace "kubeapps": unable to get app repository kubeapps/bitnami: apprepositories.kubeapps.com "bitnami" is forbidden: User "system:serviceaccount:default:example" cannot get resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapps"

you can to writh plise step by step commands ??

**Comment by absoludity** [comment] 2022-01-11 22:36
For the role to be bound in the kubeapps namespace, the role binding needs to be created in the kubeapps namespace. So in this case:

```
export KUBEAPPS_NAMESPACE=kubeapps
kubectl create -n $KUBEAPPS_NAMESPACE rolebinding example-kubeapps-applications-write
--clusterrole=kubeapps:${KUBEAPPS_NAMESPACE}:apprepositories-write
--serviceaccount default:example
```

will create the rolebinding in the kubeapps namespace so that your `default:example` service account is allowed to write apprepos in the kubeapps namespace (if that's what you intend).

Remember, check these with `kubectl` rather than kubeapps, so you can first be sure the RBAC is correct:

```
kubectl --as system:serviceaccount:default:example -n kubeapps get apprepositories
```
to check the response.

If you are unable to create the rolebinding in that namespace for other reasons, we may need to wait for #3989 mentioned above.

**Comment by refaelb** [comment] 2022-01-12 11:33
That's what I did upstairs
& Same error 

""
An error occurred: Unable to create the installed package for the package "bitnami/airflow" using the plugin "helm.packages": rpc error: code = Internal desc = Unable to create helm release "fre" in the namespace "kubeapps": Release "fre" failed and has been uninstalled: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: serviceaccounts "fre-redis" is forbidden: User "system:serviceaccount:default:example" cannot get resource "serviceaccounts" in API group "" in the namespace "kubeapps"
""

What I'm doing is wrong
thank you for all

**Comment by absoludity** [comment] 2022-01-12 23:33
> That's what I did upstairs & Same error

Sorry if I'm misunderstanding, but in your [previous comment](https://github.com/kubeapps/kubeapps/issues/4040#issuecomment-1008255199) you created the rolebinding in the `kube` namespace rather than the `kubeapps` namespace, which is why the RBAC fails I think. Ah, but you've updated that now and now see a different RBAC error when installing `bitnami/airflow`:

> 
> "" An error occurred: Unable to create the installed package for the package "bitnami/airflow" using the plugin "helm.packages": rpc error: code = Internal desc = Unable to create helm release "fre" in the namespace "kubeapps": Release "fre" failed and has been uninstalled: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: serviceaccounts "fre-redis" is forbidden: User "system:serviceaccount:default:example" cannot get resource "serviceaccounts" in API group "" in the namespace "kubeapps" ""
> 

This different RBAC error seems to indicate that you tried to create the "fre" release in the `kubeapps` namespace, which the RBAC does not allow (probably correctly, depending on what you want, but normally you'd not want to do that).

> What I'm doing is wrong thank you for all

In Kubeapps, change the namespace where you want to install `bitnami/airflow` (not sure, but based on your previous statements, this might be the `default` namespace), select `bitnami/airflow` from the catalog and deploy it there in that namespace. If the credential you are using has the correct RBAC, it will succeed.

If the credential you are using does not have the required RBAC to install a package in that namespace (`default`)  you will see an RBAC error like the ones you've seen. You can then use `kubectl` to reproduce the RBAC error without Kubeapps and fix RBAC as needed.

Hope that helps!

**Comment by absoludity** [comment] 2022-01-14 04:44
Hi @refaelb . Sorry I didn't look more closely earlier and try to reproduce this. If I had, I would have understood the problem :)

The issue is that we had a regression in that, in the past (before switching to the new API), if you authenticated as a user (or service account) who has appropriate RBAC to only one namespace (such as "user-namespace"), then you were able to install apps into that namespace from the global catalog.

When we switched to the new API server, this was no longer the case unless the authenticated user explicitly had RBAC to read the app repositories in the `kubeapps` namespace. Hence @refaelb's original error message and my attempts to get the RBAC created, but I didn't realise the root cause was because Kubeapps itself had changed. I just checked our CI, and although we do have a kubeapps-user with access to one namespace, we don't currently test deploying with that user (we should, I'll create a separate task for that).

The good news is that this is indeed already fixed in the development version and will be included in the next release. I've just verified that @castelblanque 's work on #3989 does indeed fix this (ensuring that any authenticated user can view app repositories in the kubeapps global namespace).

I'll close this as done, but please re-open it if you still have issues after upgrading to the next release (in a few weeks). In the mean-time, it should be possible to manually create the required RBAC as above.

**Closed by absoludity** 2022-01-14 04:44 UTC
Labels: awaiting-more-evidence
