### ISSUE TITLE
Kubeapps dashboard showing wrong status in multi-cluster kubernetes env

### ISSUE THREAD

**Issue by jatinderjawanda** [kubeapps/kubeapps#1006] opened 2019-04-14 16:15 UTC
Hi,
I have a multi-cluster kubernetes. Below is my kube config.
```[JJ@helm ~]# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://kubelet-remote:8383
  name: local
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://minikube:8443
  name: minikube
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-remote.local
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/node.pem
    client-key: /etc/kubernetes/ssl/node-key.pem
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
```
kubeapps pods are running under minikube cluster and minikube is hosted as VM on a actual host.

```[JJ@helm ~]# kubectl get pods -n kubeapps
NAME                                                          READY   STATUS      RESTARTS   AGE
apprepo-sync-bitnami-1555246800-bcssl                         0/1     Completed   0          161m
apprepo-sync-bitnami-1555250400-ljzcl                         0/1     Completed   0          101m
apprepo-sync-bitnami-1555254000-kbk5b                         0/1     Completed   0          41m
apprepo-sync-bitnami-8r82c-8bqz5                              0/1     Completed   0          5h16m
apprepo-sync-incubator-1555246800-bd7qd                       0/1     Completed   0          161m
apprepo-sync-incubator-1555250400-frd89                       0/1     Completed   0          101m
apprepo-sync-incubator-1555254000-nwgxj                       0/1     Completed   0          41m
apprepo-sync-incubator-bjtqf-8k97t                            0/1     Completed   0          5h16m
apprepo-sync-stable-1555246800-qlfv5                          0/1     Completed   0          161m
apprepo-sync-stable-1555250400-lt4g7                          0/1     Completed   0          101m
apprepo-sync-stable-1555254000-wb2b4                          0/1     Completed   0          41m
apprepo-sync-stable-8rxgk-ssdk7                               0/1     Completed   0          5h16m
apprepo-sync-svc-cat-1555246800-xqc5k                         0/1     Completed   0          161m
apprepo-sync-svc-cat-1555250400-j5bvq                         0/1     Completed   0          101m
apprepo-sync-svc-cat-1555254000-8ptvm                         0/1     Completed   0          41m
apprepo-sync-svc-cat-gdtk5-wr26q                              0/1     Completed   0          5h16m
kubeapps-6c5db6657d-7pglb                                     1/1     Running     0          5h17m
kubeapps-6c5db6657d-jt68g                                     1/1     Running     0          5h17m
kubeapps-internal-apprepository-controller-769948579f-jvvzq   1/1     Running     0          5h17m
kubeapps-internal-chartsvc-666b4fbb4b-7zzlg                   1/1     Running     0          5h17m
kubeapps-internal-chartsvc-666b4fbb4b-ffm4q                   1/1     Running     2          5h17m
kubeapps-internal-dashboard-64cb9bfcff-xntsk                  1/1     Running     0          5h17m
kubeapps-internal-dashboard-64cb9bfcff-xwkbj                  1/1     Running     0          5h17m
kubeapps-internal-tiller-proxy-7b6ddfd566-7vh8d               1/1     Running     0          5h17m
kubeapps-internal-tiller-proxy-7b6ddfd566-lk7jx               1/1     Running     0          5h17m
kubeapps-mongodb-5b4c46cbcc-l7xzn                             1/1     Running     0          5h17m
```

Tiller is running on host machine in client mode.

```
[JJ@helm ~]# ps -ef |grep tiller
root     23350 56292  0 11:44 pts/5    00:00:00 grep --color=auto tiller
root     61131 50736  0 06:17 pts/2    00:00:12 tiller -listen helm-host:44134 -storage secret
```
I can switch kubernetes context and able to deploy application on remote cluster(kubelet-remote).
<img width="1676" alt="Screen Shot 2019-04-14 at 8 19 20 PM" src="https://user-images.githubusercontent.com/8391344/56095472-1003d680-5efb-11e9-82ef-4044bb65e377.png">

Adding kubectl output from remote cluster where kubeapps deployed nginx application.
```
[JJ@kubelet-remote ~]# kubectl get all
NAME                               READY   STATUS    RESTARTS   AGE
pod/nginx-nginx-84d5c6c8c5-mkrlp   1/1     Running   0          1h

NAME                  TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/kubernetes    ClusterIP      10.233.0.1     <none>        443/TCP        1d
service/nginx-nginx   LoadBalancer   10.233.62.58   X.X.X.X     80:32380/TCP   1h

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-nginx   1         1         1            1           1h

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-nginx-84d5c6c8c5   1         1         1       1h
```

However, after clicking on the application from kubeapps, it still showing as "deploying" .
<img width="1678" alt="Screen Shot 2019-04-14 at 8 20 15 PM" src="https://user-images.githubusercontent.com/8391344/56095552-c071da80-5efb-11e9-8b31-afad1b7fb78d.png">

It should be showing as "deployed" not "deploying" in second page too. It seems kubeapps is assuming that is deployed in same cluster where kubeapps pod is running.

<img width="1678" alt="Screen Shot 2019-04-14 at 9 42 17 PM" src="https://user-images.githubusercontent.com/8391344/56095751-96b9b300-5efd-11e9-9500-d0bee263efa7.png">

If Tiller in client mode can deploy on remote kubernetes clusters and helm can get status from remote cluster to which tiller is pointing then kubeapps should also fetch and show right status.

```
[JJ@helm ~]# helm list
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
nginx	1       	Sun Apr 14 12:06:47 2019	DEPLOYED	nginx-2.2.1	1.14.2     	default
```

**Comment by andresmgot** [comment] 2019-04-15 17:07
Hi @jatinderjawanda,

That's right, Kubeapps assume that resources are located in the same cluster than Kubeapps. AFAIK, to modify that we would need to:

 - Make the Kubernetes host configurable in the frontend ConfigMap:
https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/kubeapps-frontend-config.yaml#L37
 - Make tiller-proxy point to the different cluster (avoid using the default):
https://github.com/kubeapps/kubeapps/blob/master/cmd/tiller-proxy/main.go#L81

The first item can be work around if you modify the ConfigMap. Could you give it a try? You can edit the line I point above (and restart the pod) executing:

```
kubectl edit -n kubeapps configmap kubeapps-frontend-config
kubectl delete pod -n kubeapps -l app=kubeapps
```

The second is more difficult to handle but it's only used to check that the user have permissions to perform a certain action so you should be able to perform an action in the cluster `local` if you have permissions to do so in `minikube`.

**Comment by prydonius** [comment] 2019-04-19 00:23
> If Tiller in client mode can deploy on remote kubernetes clusters and helm can get status from remote cluster to which tiller is pointing then kubeapps should also fetch and show right status.

To clarify a bit more about this point, whilst we get some information regarding the chart release from Tiller, we need to get more up-to-date information about the state from the Kubernetes API directly.

It looks like you already solved the second point mentioned by @andresmgot, is that correct? How did you get Kubeapps to point to your local Tiller?

**Comment by andresmgot** [comment] 2019-04-19 16:19
> It looks like you already solved the second point mentioned by @andresmgot, is that correct? How did you get Kubeapps to point to your local Tiller?

`tiller-proxy` has available the same flags than the `helm` CLI. I assume that @jatinderjawanda modified the default flags to point to the local Tiller.

**Comment by jatinderjawanda** [comment] 2019-04-22 08:03
@andresmgot : Yes, you're right I used the flag to point it to local tiller.

I tried the first option by editing frontend configMap but it didn't work.

**Comment by jatinderjawanda** [comment] 2019-04-22 09:41
> > If Tiller in client mode can deploy on remote kubernetes clusters and helm can get status from remote cluster to which tiller is pointing then kubeapps should also fetch and show right status.
> 
> To clarify a bit more about this point, whilst we get some information regarding the chart release from Tiller, we need to get more up-to-date information about the state from the Kubernetes API directly.

I think when fetching status using kubernetes api, first get the api server then only send the rest call to that particular kubernetes cluster. 

Often, tiller is not allowed to run on remote kubernetes clusters.

**Comment by andresmgot** [comment] 2019-04-22 17:17
> I tried the first option by editing frontend configMap but it didn't work.

Just to double check, after modifying the configmap, did you restart the pod? It's necessary to reload the changes. Are you receiving the same error? It's still trying to do the HTTP request to the wrong Kubernetes cluster?

**Comment by jatinderjawanda** [comment] 2019-04-22 17:22
Yes, I restarted the pods. I changed it to `proxy_pass https://<remote_kube_api_server>:8443`
but then kubeapps pods started crashing.

**Comment by andresmgot** [comment] 2019-04-22 17:26
what's the cause of the crash? What's in the logs?

**Comment by jatinderjawanda** [comment] 2019-04-22 17:45
<img width="1679" alt="Screen Shot 2019-04-22 at 11 15 02 PM" src="https://user-images.githubusercontent.com/8391344/56514786-ddd62280-6553-11e9-93d5-f76ca91bc820.png">

I tried first option again this time using IP address of remote kubernetes api server and pods are in `RUNNING` state. 
Logs from pods.
```
kubectl logs -f kubeapps-6c5db6657d-gl7p7 -n kubeapps

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues

INFO  ==> nginx.conf not found. Applying bitnami configuration...
INFO  ==> Starting nginx...
172.17.0.1 - - [22/Apr/2019:17:31:56 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.14"
172.17.0.1 - - [22/Apr/2019:17:32:06 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.14"
172.17.0.1 - - [22/Apr/2019:17:32:16 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.14"
172.17.0.1 - - [22/Apr/2019:17:32:26 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.14"
172.17.0.1 - - [22/Apr/2019:17:32:36 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.14"
```
However,I am not able to login into kubeapps page even after giving token.

**Comment by prydonius** [comment] 2019-04-22 21:23
@jatinderjawanda looks a little more promising, but strange that you now cannot login.

Are you able to `curl -H "Authorization: Bearer $TOKEN" https://<remote_kube_api_server>:8443/api/kube` with the same Authorization token you're logging in with?

**Comment by jatinderjawanda** [comment] 2019-04-23 06:27
@prydonius: Remote kubernetes api server is running on 8383 port and I tried using same but no luck.
If you check the screenshot, the rest call is still pointing to local ip where kubeapps pod is running
`https://<local cluster ip>:<port>/api/kube` but I think it should have IP of remote cluster which I passed in `proxy_pass https://<remote_kube_api_server>:8383/api/kube`
Correct me If I am wrong.

**Comment by andresmgot** [comment] 2019-04-23 17:35
> If you check the screenshot, the rest call is still pointing to local ip where kubeapps pod is running
https://<local cluster ip>:<port>/api/kube but I think it should have IP of remote cluster which I passed in proxy_pass https://<remote_kube_api_server>:8383/api/kube
Correct me If I am wrong.

Yes, there it should be using the Kubeapps URL, the proxy pass will be done internally so you won't see it in the browser console.

What it's not clear to me is that if `curl -H "Authorization: Bearer $TOKEN" https://<remote_kube_api_server>:8383/` worked for you? That should work, in other case the token is not valid.

**Comment by jatinderjawanda** [comment] 2019-04-23 18:20
> What it's not clear to me is that if `curl -H "Authorization: Bearer $TOKEN" https://<remote_kube_api_server>:8383/` worked for you? That should work, in other case the token is not valid.

curl command Output:- 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
```
When I changed the settings back `https://kubernetes.default` then same token works.

**Comment by andresmgot** [comment] 2019-04-23 23:22
So that's apparently the problem, you are using a token valid for the cluster hosting kubeapps (I think you called it `minikube`) while you should be using one for the cluster you are running the Kubernetes API (`kubelet`). If you use that token, the command `curl -H "Authorization: Bearer $TOKEN" https://<remote_kube_api_server>:8383/ ` should work and then you can use that token to access kubeapps.

**Comment by jatinderjawanda** [comment] 2019-04-24 06:53
> So that's apparently the problem, you are using a token valid for the cluster hosting kubeapps (I think you called it `minikube`) while you should be using one for the cluster you are running the Kubernetes API (`kubelet`). If you use that token, the command `curl -H "Authorization: Bearer $TOKEN" https://<remote_kube_api_server>:8383/ ` should work and then you can use that token to access kubeapps.

I am confused here. Actually, I generated token on local cluster not on remote cluster for kubeapps and the idea is to deploy from everything from local cluster without touching the remote cluster. And, If I have to use token from remote cluster then for whom I should create a token on remote cluster?

Need guidance here.

**Comment by andresmgot** [comment] 2019-04-24 16:27
I am not sure I follow your goal. From your first comment you said:

> I can switch kubernetes context and able to deploy application on remote cluster(kubelet-remote).

> It seems kubeapps is assuming that is deployed in same cluster where kubeapps pod is running.

From that I understand that you want to install apps in the remote cluster.

Do you want to deploy applications in your local cluster, where Kubeapps is running? If that's the case you are only working with a single cluster, you don't need the remote cluster at all. If you want to install apps in the remote cluster then you need to use the token valid the remote cluster.

**Comment by absoludity** [comment] 2020-09-29 06:41
Closing as the multi-cluster support (though different) enables this now.

**Closed by absoludity** 2020-09-29 06:41 UTC
Labels: kind/feature, priority/low
