### ISSUE TITLE
"has no deployed releases" limbo-state

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1163] opened 2019-09-10 13:14 UTC
If you do an initial install, which fails, you'll get into an invalid state where a redeploy ends in "Unable to update the release: rpc error: code = Unknown desc = “aot-ccm-fs-mon-ws-p1” has no deployed releases"
and the only way to fix this is to do a `helm del --purge aot-ccm-fs-mon-ws-p1` and then go through the whole workflow of deploying again.

kubeapps should notice this and allow deployment to continue.

**Comment by andresmgot** [comment] 2019-09-11 11:10
Thanks for reporting this @davidkarlsen, we will investigate the bug

**Comment by absoludity** [comment] 2019-09-17 02:02
It took me a while, but I've tried to reproduce this with the following:

1. Choose the bitnami/wordpress chart,
2. In the `values.yaml` for the key `PullPolicy` update the value to `NotAPullPolicy`
3. Install, and see the error:
![1163-a-failed-deploy](https://user-images.githubusercontent.com/497518/65004077-71aeed80-d93e-11e9-9e2d-b7dbfab7e35a.png)

4. Verify the helm release is failed:
```
$ helm ls wordpress
NAME            REVISION        UPDATED                         STATUS  CHART           APP VERSION     NAMESPACE
wordpress       1               Tue Sep 17 01:28:41 2019        FAILED  wordpress-7.3.4 5.2.3           kubeapps 
```
5. Update the pull policy in the values.yaml to `IfNotPresent` and click submit to see "Already Exists":
![1163-b-already-exists](https://user-images.githubusercontent.com/497518/65004150-be92c400-d93e-11e9-9f5b-025f8214966f.png)
6. Click on `Applications` to see Wordpress listed as a failed release. Click on it, then Upgrade to see "No deployed releases" as reported:
![1163-c-no-deployed-releases](https://user-images.githubusercontent.com/497518/65004228-06b1e680-d93f-11e9-9834-9f6f3caa24c8.png)
7. In the Kubeapps dashboard, select the app again, and delete with purge,
8. Deploy the chart again with valid values and it installs fine.

The thing is, this appears to be helm's default behaviour:
```
$ helm install --name wordpress --set image.pullPolicy=NotAPullPolicy bitnami/wordpress                                                                                                
Error: release wordpress failed: Deployment.apps "wordpress" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "NotAPullPolicy": supported values: "Always", "IfNotPresent", "Never"

$ helm list wordpress
NAME            REVISION        UPDATED                         STATUS  CHART           APP VERSION     NAMESPACE
wordpress       1               Tue Sep 17 01:43:23 2019        FAILED  wordpress-7.2.2 5.2.2           default  

$ helm install --name wordpress  bitnami/wordpress                                                                                                                                     
Error: a release named wordpress already exists.
Run: helm ls --all wordpress; to check the status of the release
Or run: helm del --purge wordpress; to delete it

$ helm upgrade wordpress bitnami/wordpress
UPGRADE FAILED
ROLLING BACK
Error: "wordpress" has no deployed releases
Error: UPGRADE FAILED: "wordpress" has no deployed releases

$ helm delete --purge wordpress
release "wordpress" deleted

$ helm install --name wordpress  bitnami/wordpress
NAME:   wordpress
LAST DEPLOYED: Tue Sep 17 01:47:49 2019
NAMESPACE: default
...

$ helm list wordpress
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
wordpress       1               Tue Sep 17 01:47:49 2019        DEPLOYED        wordpress-7.2.2 5.2.2           default  
```

So related to:
> kubeapps should notice this and allow deployment to continue

I'm not sure Kubeapps should purge a prior release when upgrading ever, if that's what you mean? (Especially since helm has the same behaviour as shown).

To me it seems odd (both in the helm CLI and kubeapps) that you can end up in this state when installing - that the release is considered there and not there (depending whether you're later trying to re-install or upgrad).

One option, which would lead to a consistent experience in the UI, is to use the `--atomic` flag when Kubeapps installs the chart, which would be consistent with the helm client:
```
$ helm install --name wordpress --set image.pullPolicy=NotAPullPolicy --atomic bitnami/wordpress
INSTALL FAILED
PURGING CHART
Error: release wordpress failed: Deployment.apps "wordpress" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "NotAPullPolicy": supported values: "Always", "IfNotPresent", "Never"
Successfully purged a chart!
Error: release wordpress failed: Deployment.apps "wordpress" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "NotAPullPolicy": supported values: "Always", "IfNotPresent", "Never"
$ helm list wordpress
$ 
```
So when an install fails you'd be able to re-submit the correct values.yaml without issue, and you would never be able to upgrade an install that failed to install in the first place.

Does that make sense to you?

**Comment by davidkarlsen** [comment] 2019-09-17 06:33
Linking relevant issue: https://github.com/helm/helm/issues/5875
Two options come to mind: 
1) expose an atomic toggle option
2) expose a purge option

**Comment by absoludity** [comment] 2019-09-17 06:54
Thanks for the heads-up about the helm issue - we'll need to safely work around that (until it's fixed in helm), but that should be simple enough (in tiller-proxy). Do you otherwise see a reason Kubeapps shouldn't just use `--atomic` when installing by default, as above? (whether or not we later expose deployment options in the UI for those type of helm args).

**Comment by davidkarlsen** [comment] 2019-09-17 07:00
I don't see a reason for not using atomic - just got scared off by the bug :)
I haven't used the option - but I will turn it on in my CI pipeline (non-interactive) - as I have seen similar problem there.

**Comment by andresmgot** [comment] 2019-09-23 08:38
:+1: 

I think using the `atomic` flag should be fine. Also we can add the check to fail earlier in the install process if the release name already exists (if we don't do that already).

**Closed** 2019-12-03 10:53 UTC
Labels: kind/bug, priority/high
