### ISSUE TITLE
Assetsvc should always return global NS charts

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1845] opened 2020-07-03 03:30 UTC
### Description:

If Kubeapps configure only a global AppRepo, catalog works properly but upgrade cannot get charts list correctly.

I use MongoDB so I check the mongo util, I take a glance in postgresql part and seems that contains same problem.

In commit `be439bd`, in file `mongodb_util.go`, function `getPaginatedChartList` (used by Catalog page) add a `namespace` parameter, which filter charts list.
https://github.com/kubeapps/kubeapps/commit/be439bd8e44d2aec2558af0b370ee55e1131cf75#diff-7126ef4d2f66de2097aeebf49d710c6cR44-R52
```go
func (m *mongodbAssetManager) getPaginatedChartList(namespace, repo string, pageNumber, pageSize int, showDuplicates bool) ([]*models.Chart, int, error) {
        // ...
	if namespace != dbutils.AllNamespaces {
		matcher["repo.namespace"] = namespace
	}
        // ....
```

And commit `6f1ea36` supports global AppRepo (by check env var POD_NAMESPACE),
https://github.com/kubeapps/kubeapps/commit/6f1ea36e693dd0f94bcb6bb26183ea63f774d78f#diff-7126ef4d2f66de2097aeebf49d710c6cR46
```go
	if namespace != dbutils.AllNamespaces {
		matcher["repo.namespace"] = bson.M{"$in": []string{namespace, m.KubeappsNamespace}}
	}
```

But the other functions change nothing, such as `getChartsWithFilters`, which used by the `update available` check.
https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/mongodb_utils.go#L136

```go
func (m *mongodbAssetManager) getChartsWithFilters(namespace, name, version, appVersion string) ([]*models.Chart, error) {
	// ...
	err := db.C(chartCollection).Find(bson.M{
		"repo.namespace": namespace,
		// .... 
	}).All(&charts)
	return charts, err
}
```

I think if there is a concept call *global* NS, it should work everywhere?

### Steps to reproduce the issue:

1. Configure a AppRepo in global NS (mostly is `kubeapps`)
2. Install a chart in another NS
3. Update the chart
4. In `Applications` page, `Update Available` sign won't show in the app card
5. If click upgrade button in apps detail page, got an warning `Chart repository not found`

In inspector network panel, can find calls to `api/assetsvc/v1/ns/{ns-name}/charts?name={chart-name}&version={installed-version}&appversion={intalled-appversion}`, which returns empty array.

### Describe the results you expected:

Upgrade should work.

**Comment by andresmgot** [comment] 2020-07-03 07:40
hi @lingsamuel,

Thanks for the detailed bug report! I am a bit confused though, a global AppRepo is an apprepository installed in the `kubeapps` namespace. Are you creating that global repo in that namespace? The steps you mention to reproduce the issue are covered by Kubeapps end-to-end tests so it's not reproducible.

There was indeed a bug like the one you described but for namespaced repositories: https://github.com/kubeapps/kubeapps/issues/1815
We fixed that already but it won't be available for users until the next release.

**Comment by lingsamuel** [comment] 2020-07-03 09:38
Hi @andresmgot,
Yes the global repo I mentioned is in `kubeapps` namespace, it's the only app repo I have.
I noticed the issue you point before I submit this issue, but I think there is another bug.

I know almost nothing about the frontend so I can't find how the page works in code.
But I noticed that in the `Applications` page (url like `/ns/{namespace-name}/apps`) and the `Upgrade` page (url like `/ns/{namespace}/apps/{release-name}/upgrade`), they both call the `assetsvc` API `/ns/{namespace}/charts?name=xxx&version=xxx&appversion=xxx`, which returns empty array.

This API internally doesn't add the `kubeapps` namespace to the query option, so the query match only the namespace release in, which doesn't have any chart data in mongodb, cause the result array is empty.

I make a minor fix locally solve the issue:
```go
func (m *mongodbAssetManager) getChartsWithFilters(namespace, name, version, appVersion string) ([]*models.Chart, error) {
	db, closer := m.DBSession.DB()
	defer closer()
	var charts []*models.Chart
	matcher := bson.M{
		"repo.namespace": namespace,
		"name":           name,
		"chartversions": bson.M{
			"$elemMatch": bson.M{"version": version, "appversion": appVersion},
	}}

	if namespace != m.KubeappsNamespace {
                // this line fix the problem
		matcher["repo.namespace"] = bson.M{"$in": []string{namespace, m.KubeappsNamespace}}
	}
	err := db.C(chartCollection).Find(matcher).Select(bson.M{
		"name": 1, "repo": 1,
		"chartversions": bson.M{"$slice": 1},
	}).All(&charts)
	return charts, err
}
```
![image](https://user-images.githubusercontent.com/14567045/86455672-8b95b180-bd53-11ea-98b0-b149079669ee.png)

I am not sure whether this fix will introduce new bug, but it works well for me.

**Comment by andresmgot** [comment] 2020-07-03 13:17
> I know almost nothing about the frontend so I can't find how the page works in code.
> But I noticed that in the `Applications` page (url like `/ns/{namespace-name}/apps`) and the `Upgrade` page (url like `/ns/{namespace}/apps/{release-name}/upgrade`), they both call the `assetsvc` API `/ns/{namespace}/charts?name=xxx&version=xxx&appversion=xxx`, which returns empty array.

Yes, that's the weird thing, the bug fixed in #1815 was that the namespace used in the call `/ns/{namespace}/charts?name=xxx&version=xxx&appversion=xxx` was always `kubeapps` which caused repos in other namespaces to not be taken into account. If your repository is in the `kubeapps` namespace, the call `/ns/kubeapps/charts?name=xxx&version=xxx&appversion=xxx` should return your chart.

> I make a minor fix locally solve the issue:

From your change, I suspect that the request is not `/ns/kubeapps/...` since you are just adding `kubeapps` to the array of namespaces. Can you confirm that's the link you are seeing?

Also, which version of Kubeapps are you running? Note that in the latest versions, MongoDB has been deprecated in favor of Postgres.

**Comment by lingsamuel** [comment] 2020-07-06 06:51
Assume my app deployed at NS `test`.
My dashboard are synced with newest commit, which means it has #1816 changes.
The request are `/ns/test/...`, which makes `assetsvc` won't return charts in `kubeapps`.

**Comment by andresmgot** [comment] 2020-07-06 07:30
> My dashboard build are synced with newest commit, which means it has #1816 changes.

I don't recommend you to use the latest commit for two reasons. The first is that you need to also update all the other components, some changes in the dashboard require changes in the other services (like the assetsvc or kubeops). You may be hitting an issue due to cached images. The second reason is that even if we check that we don't break functionality with end-to-end tests, we don't fully check the application until we prepare a release, this means that you may be hitting new bugs.

I'd recommend you (if you are not using namespaced repositories) to use the latest version released. It's available here: https://github.com/bitnami/charts/tree/master/bitnami/kubeapps

**Comment by lingsamuel** [comment] 2020-07-06 08:59
You are right.
I revert to `3.7.2` and the request always be `/ns/kubeapps/...`.

**Closed** 2020-07-06 09:03 UTC
