### ISSUE TITLE
Error with kubeapps up on Windows

### ISSUE THREAD

**Issue by vyfster** [kubeapps/kubeapps#127] opened 2018-02-16 10:08 UTC
I get the following error when running `kubeapps up` on Windows 10 with minikube.

```
[31mERRO[0m[0000] can't verify Kubernetes version: strconv.Atoi: parsing "": invalid syntax
```

Versions of minikube, kubectl and kubeapps :

```
PS > kubeapps version
Kubeapps Installer version: devel
```
Although kubeapps version says `devel`, I got this from the GIthub releases page.  It should probably be 0.2.0.

```
PS > minikube version
minikube version: v0.25.0
```

```
PS > kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by prydonius** [comment] 2018-02-16 10:15
Hey @vyfster, this actually isn't a specific Windows issue, but actually an issue in Kubernetes 1.9 (that was fixed in later versions, but for some reason not included in Minikube). You can try Kubeapps on Kubernetes 1.8 instead using: `minikube start --kubernetes-version=v1.8.0`.

**Comment by vyfster** [comment] 2018-02-16 10:38
Thanks @prydonius.  I want to use k8s v1.9 so I'll have to wait until minikube supports a "fixed" version of k8s :)

**Comment by arapulido** [comment] 2018-02-16 10:46
I will close this issue, as it is not caused by Kubeapps. @vyfster, let us know if you need anything else!

**Closed by arapulido** 2018-02-16 10:46 UTC
