### ISSUE TITLE
Very slow response time from kubeops backend requests

### ISSUE THREAD

**Issue by mecampbellsoup** [kubeapps/kubeapps#2506] opened 2021-03-04 20:07 UTC
### Description:

When kubeapps is deployed to a cluster that has a large number of namespaces (e.g. > 100), at least one endpoint i.e. `/backend/v1/clusters/default/namespaces` becomes very slow:
```
[negroni] 2021-03-03T23:25:59Z | 200 |   23.2154635s | chi-tenant-kubeapps-internal-kubeops:8080 | GET /backend/v1/clusters/default/namespaces
```
In our case this request _always_ takes 23s+ in duration to resolve w/ 200 OK.

### Steps to reproduce the issue:

1. Create a kubernetes cluster and deploy kubeapps into it.
2. Write a simple bash script to create some large number of namespaces in the cluster.
3. Load the kubeapps dashboard paying particular attention to the proxied request `/api/v1/clusters/default/namespaces`; it will take a very long time to respond.

### Additional information you deem important (e.g. issue happens only occasionally):

We have discussed this issue and reproduced it with kubeapps maintainers - for context see the [Slack conversation](https://kubernetes.slack.com/archives/C9D3TSUG4/p1614807084007900).

### Implementation Proposal(s)

@salanki will be updating this issue with an implementation proposal.

The specific spot in the Golang codebase (i.e. kubeops repo) that leads to the latency is where every namespace in the cluster is checked for being accessible by kubeapps or not:

* https://github.com/kubeapps/kubeapps/blob/9356f12b8307f8e3f2764023be461249725a1d43/pkg/kube/kube_handler.go#L803
* https://github.com/kubeapps/kubeapps/blob/9356f12b8307f8e3f2764023be461249725a1d43/pkg/kube/kube_handler.go#L755-L764

In our case, kubeapps will sit behind our API gateway which sets proxy headers including `X-Consumer-Permissions` (a list of permission including *namespaces the user can access*). Ideally we could provide to kubeapps our own definition for "what namespaces can the logged in user/account interact with" - but we aren't too sure how to make such functionality more generic (i.e. a generic way to tell kubeapps what namespaces a user/account can access).

**Comment by andresmgot** [comment] 2021-03-05 08:23
Thanks @mecampbellsoup, I'd suggest a couple of generic improvements:

 - Request the namespaces in parallel. As you can see, in kubeops code the namespaces are checked one by one. If we set a pool of ~10 workers that should reduce the time spent significally.
 - If the first is not enough, cache the response so at least the second time the list of resources is requested is instantaneous.

**Comment by salanki** [comment] 2021-03-05 18:02
I think parallelization will solve it for up to 50 namespaces. It won't scale in an environment with 100+ namespaces. I don't think caching is the right approach here. The UX will still be bad on first load, and having to deal with cache consistency is always a pain.

We should to add support to read the list of namespaces from somewhere, this could be ie.

1) Read a resource in Kubernetes, such a s a ConfigMap
2) Have the auth-provider set a header or a cookie with the list of allowed namespaces. If Kubeapps finds said header or cookie, it will read from there, otherwise it will use the method described in your comment.

**Comment by absoludity** [comment] 2021-03-08 01:07
> We should to add support to read the list of namespaces from somewhere, this could be ie.
> 
>     1. Read a resource in Kubernetes, such a s a ConfigMap

This won't work per-user though? Maybe that's not relevant for your use-case, or maybe you mean to define multiple values for different users/teams?
 
>     2. Have the auth-provider set a header or a cookie with the list of allowed namespaces. If Kubeapps finds said header or cookie, it will read from there, otherwise it will use the method described in your comment.

+1 for this option or something like it. Could we assume an interface for something like `namespacesForRequest()`, the implementation of which can be optionally configured by operators, with the default implementation returning nil. The frontend code can then, as you say, only request namespaces from the backend if the function returns nil. Only reason I mention this is that it'd be nice not to assume in the Kubeapps codebase how the namespaces can be discovered (ie. so we don't hard-code the solution used by your custom auth proxy). Thoughts?

**Comment by andresmgot** [comment] 2021-03-08 09:07
> > ```
> > 2. Have the auth-provider set a header or a cookie with the list of allowed namespaces. If Kubeapps finds said header or cookie, it will read from there, otherwise it will use the method described in your comment.
> > ```
> 
> 
> +1 for this option or something like it. Could we assume an interface for something like `namespacesForRequest()`, the implementation of which can be optionally configured by operators, with the default implementation returning nil. The frontend code can then, as you say, only request namespaces from the backend if the function returns nil. Only reason I mention this is that it'd be nice not to assume in the Kubeapps codebase how the namespaces can be discovered (ie. so we don't hard-code the solution used by your custom auth proxy). Thoughts?

My concern with that solution is that it will be static. If every time a namespace is created, the operator needs to update Kubeapps, that won't scale. Also it may be weird for users that want to use a namespace that they have just created.

Another option would be just avoid the filtering if the user has permissions to list namespaces. That's how all the Kubernetes dashboards work. In that case, people with permissions to list namespaces will get an instantaneous response. (Also, we could disable the namespace filter feature by configuration?).

**Comment by salanki** [comment] 2021-03-09 02:15
1. I don't understand what you mean by static. In our case, the auth-proxy will populate headers and possibly a cookie on every request with every namespace the user has access to. `namespacesForRequest` would be in Go or JS? If Go, is there already a pattern to extend the go pieces of Kubeapps without a fork?

2. In our case, users don't have access to list namespaces, so that does not help. I have a faint memory of the Kubernetes dashboard working correctly for our users, by just using their auth token, so maybe they have figured out a way to get the namespace.

**Comment by absoludity** [comment] 2021-03-09 02:29
> 
> My concern with that solution is that it will be static. If every time a namespace is created, the operator needs to update Kubeapps, that won't scale.

It's a header or cookie being set by the auth proxy. So yet there could be some sync issues when you're already logged in and a namespace is created to which you have access (unless the auth-proxy updates the cookie).

> Also it may be weird for users that want to use a namespace that they have just created.

We can add it to the state directly when added.

> 
> Another option would be just avoid the filtering if the user has permissions to list namespaces. That's how all the Kubernetes dashboards work. In that case, people with permissions to list namespaces will get an instantaneous response.

Currently we'd still iterate those to determine which ones the user has access to I think? Though we could choose not to do that if the user can list namespaces.

> (Also, we could disable the namespace filter feature by configuration?).

Yes, this could be useful (I think if RBAC for the kubeops service account doesn't give access, it'll just leave it empty).

>   I have a faint memory of the Kubernetes dashboard working correctly for our users, by just using their auth token, so maybe they have figured out a way to get the namespace.

Yes, (service account) auth tokens include the namespace of the token which can be used (Kubeapps used that when people auth with a service-account token), but in a multi-user env, we can't encourage people logging in with a service-account token. And knowing the single namespace that is relevant to a user is not .... oh, actually, perhaps that's your use-case? That each user has a namespace? It could have been included in the jwt token but from memory you're not keen to use those for auth, but your auth-service providing it/them in a header or cookie sounds useful.

**Comment by salanki** [comment] 2021-03-09 03:36
In our case, users can have access to one or multiple namespaces. Our auth-proxy can provide a list like `X-Consumer-Permitted-Namespaces: ["namespace1","namespace2"]`

**Comment by andresmgot** [comment] 2021-03-09 09:10
> In our case, users can have access to one or multiple namespaces. Our auth-proxy can provide an up to date list like `X-Consumer-Permitted-Namespaces: ["namespace1","namespace2"]` with every request.

My question is how that header is set. If it's manual, what happens when there is `namespace3`? An operator would need to update the permitted namespaces for all users?

Or if it's automatic, the problem is the same than in `kubeops`, isn't it?

**Comment by salanki** [comment] 2021-03-11 21:13
That header is set on every request, in our API Gateway. The API gateway has an up to date list of permitted namespaces a user has access to in it's database, it does not ask Kubernetes about it on every request. Our implementation doesn't use [Kong](https://docs.konghq.com/), but you could implement this using Kong [acls](https://docs.konghq.com/hub/kong-inc/acl/) and the `X-Consumer-Groups` header.

To make this as flexible as possible, it could be configured by two env vars in Kubeapps:
```
AUTH_PROXY_NAMESPACE_HEADER = "X-Consumer-Groups"
AUTH_PROXY_NAMESPACE_PATTERN = "(([_\w-]+),)+"
```
The regex pattern would be applied to the consumer groups, and whatever the capture group extracts will be in the namespace list. The pattern above (if I got my regex right, which I probably didn't) will extract the namespaces test & apps from `Header X-Consumer-Groups: test,apps`.

**Comment by andresmgot** [comment] 2021-03-12 08:14
> The API gateway has an up to date list of permitted namespaces a user has access to in it's database, it does not ask Kubernetes about it on every request

While that's a completely valid solution, it won't be available for most of Kubeapps users. If your team wants to contribute with that solution it will be more than welcomed but we will still need to address the issue for the rest of users with a solution generic enough.

**Closed** 2021-03-23 14:58 UTC
Labels: size/M

**Comment by mecampbellsoup** [comment] 2021-03-29 16:23
@andresmgot @absoludity the parallelization is a step in the right direction but is unlikely to work in our use-case where we will have thousands of namespaces in a tenant cluster.

We can prepare a PR supporting option number 2 in [@salanki comment](https://github.com/kubeapps/kubeapps/issues/2506#issuecomment-791586675) but want to make sure we have your buy-in first...

**Comment by absoludity** [comment] 2021-03-30 00:56
> We can prepare a PR supporting option number 2 in [@salanki comment](https://github.com/kubeapps/kubeapps/issues/2506#issuecomment-791586675) but want to make sure we have your buy-in first...

I'm +1 for a solution that enables your auth-proxy to provide the namespaces for the user, but not so keen on a solution which is specific to your custom auth-proxy that others would have to follow (ie. that your auth-proxy sets a cookie with the namespaces, or sets a header that the dashboard client code checks for a specific value).

A more generic solution would be that the dashboard makes an auth'd request to a configured endpoint (including the cluster name) which returns the namespaces for that user? Your auth-proxy could provide that endpoint, but it also allows us to:

* by default use the existing endpoint in the backend, and
* allows other users to add the same for their own custom setups in a generic way.

Does that work for you?

**Comment by salanki** [comment] 2021-03-30 00:59
My suggested solution should play well with any API Gateway, such as Kong, not only our own (HAProxy).

**Comment by andresmgot** [comment] 2021-03-30 07:57
Yes, my +1 too if the solution is generic.

**Comment by absoludity** [comment] 2021-03-31 00:31
> My suggested solution should play well with any API Gateway, such as Kong, not only our own (HAProxy).

Yes of course - I didn't mean your solution wouldn't work with other reverse proxies, just that other users then have to follow the same method which may or may not be the best for everyone.

If we ask (without thinking about specific technologies): "what should users be required to provide to enable efficient retrieval of namespaces for a specific user?" then to me currently the simplest requirement would be that they provide an authenticated endpoint that returns the namespaces for a user.

On the other hand, if you think the simplest solution (not for you, but generally for users of Kubeapps) would be for users to ensure that Kubeapps sits behind an API gateway (or special functionality that they implement on the existing HAProxy) such that each request includes a `Kubeapps-User-Namespaces` header with the namespaces, then I'd like to understand why. I'm not saying it's not (yet), I just don't yet understanding how that could be a better, simpler requirement for users generally? 

That said, having the dashboard use a header if it exists rather than making the expensive call may be a small footprint (not sure), and if so, I'm OK with including it (as we can easily later extend that to fall through  eg. 1. check for header and use if present, 2. check for custom endpoint, 3. fall back to default inefficient endpoint).

Have you looked at how small or large the change would be to the frontend code to do what you want?

**Comment by salanki** [comment] 2021-03-31 00:33
We are looking into the change. I do not think this is necessarily the easiest solution for everyone, but for the people who use API Gateways it is a very good solution. Doesn't exclude other solutions to be developed, we just want to make sure we can get it merged!

**Comment by absoludity** [comment] 2021-03-31 00:57
Yep, understood. So the two relevant bits of information are:

1. How simple (or complex) would the dashboard change be to accommodate your proposal, and
2. How simple (or complex) would it be for you to instead implement an auth'd API endpoint (given your HA proxy already has this info) and we'll happily add the option to configure one.

I'm keen to support this, but want to be sure that the right decision is made for Kubeapps. If you can show that (1) is simple in the dashboard code, happy to merge. Otherwise if it's not going to be simple, I'd strongly recommend we look at 2 as the easiest solution for everyone.

**Comment by mecampbellsoup** [comment] 2021-04-05 17:50
This is extremely pseudo-codey but, this feels like it would be generic to me:

```yaml
kubeops:
  customNamespaceAuth:
    headerName: x-consumer-permissions
    func: |-
      # Evaluated in the context of the Golang kubeops backend
      function ParsePermissionsHeader(req: Request) {
        allPermissions = req.Headers.get(.Values.kubeops.customNamespaceAuth.headerName) # Set by our gateway
        nsPerms = allPermission.filter(matchesNamespace).match(/read/)
        return nsPerms
      }
```
Note that I don't think Golang has the ability to `eval()` some text to make a Go func at runtime (`customNamespaceAuth.func` in this example) so this idea might be garbage - hopefully at least it conveys what we mean by "defining and setting some generic header that contains the whitelist of namespaces".

**Comment by andresmgot** [comment] 2021-04-06 08:20
I don't think that we need to have dynamic code here (since this would work with the namespace endpoint only). If the header (`x-consumer-permissions`) reaches kubeops we can just evaluate it [there](https://github.com/kubeapps/kubeapps/blob/master/pkg/http-handler/http-handler.go#L245) (and document how to set up that env).

**Comment by absoludity** [comment] 2021-04-12 03:10
Sorry, I've been away and just catching up.

> I don't think that we need to have dynamic code here (since this would work with the namespace endpoint only). If the header (`x-consumer-permissions`) reaches kubeops we can just evaluate it [there](https://github.com/kubeapps/kubeapps/blob/master/pkg/http-handler/http-handler.go#L245) (and document how to set up that env).

If the format of the header value is a well-known format that can be parsed, sure (for eg., if it was a json string, then the config could pass a `jsonpath` or similar to get the namespaces so that no custom code is required), but if we're meaning a custom format for use here that requires a filtering+regex, that others will be forced to use, I'm not so keen unless it's accompanied by a specific config option to use that parse function (ie. it's not default).

That is, I agree we don't need dynamic code here (unless it is just a URL to call an external FAAS which returns the namespaces for the request/header), but I don't think we can just use a custom parse function by default.

So, if `kubeops.customNamespaceAuth.headerName` is set, then by default we could expect the value to be a list of namespaces, *unless* a custom parse function is identified by `kubeops.customNamespaceAuth.parseFunction=companyXParseNamespacesFromPerms` with the implementation in the kubeops code. That way, our default parsing is simple and generic, but this current use-case can easily be accommodated? We still end up with custom parse code in kubeops (not ideal when compared to just a FAAS url), but it's not a default, and we can later add support for tanzu perms for eg, if required.

**Comment by mecampbellsoup** [comment] 2021-04-12 12:46
After giving this some more consideration, I think the by-far _easiest_ approach would be to allow 2 custom values to be set:

1. `customNamespaceAuth.headerName`
2. `customNamespaceAuth.headerRegex`

This way API gateway users like us where the "ns whitelist" is driven by permissions, and permissions are written by the gateway into a proxied request header (`x-consumer-perms` in our example) have very little extra effort to do.

If that isn't generic enough we can probably implement an FAAS endpoint approach (where we specify some internal URL to query to get the ns whitelist) but it's an extra roundtrip. That said I would have to concede that an FAAS approach feels more generic than expecting everyone to do what we do, i.e. set the user's accessible namespaces into a proxied request header at the gateway as part of authentication.
