### ISSUE TITLE
Test Pinniped 0.7 and managed k8s

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2662] opened 2021-04-11 20:12 UTC
One of the features of the pinniped 0.7 release is that Pinniped Concierge (which we use) now support for managed K8s (EKS, AKS, GKE) using impersonation.

In addition to the normal check that 0.7 works with our current setup, we'll need to update pinniped-proxy to additionally support the impersonation method.

**Comment by antgamdia** [comment] 2021-04-14 15:09
I can confirm that the local setup with Pinniped 0.7 in self-managed environments is working (no need to performs further changes) as usual.

However, as expected, it does not work in managed k8s envs (testing AKS atm):

![image](https://user-images.githubusercontent.com/11535726/114733672-d82b0600-9d43-11eb-875b-d3e5a4a05776.png)

Good news is that is not a 401 but an error while exchanging credentials. I'm having a look at it so that we really know which changes are required from our end to support this use case.

**Comment by absoludity** [comment] 2021-04-15 00:41
AFAIK, concierge now has two modes. Interested to see what the difference is for us!

**Comment by antgamdia** [comment] 2021-04-16 15:51
Some updates so far (I'll be editing this comment to ad further details)


## New features in Pinniped

There is no new authentication mechanism (afaik), the key part is still based upon a `TokenCredentialRequest`, so the whole pinniped-proxy logic is still valid.

The point here is to whom we should communicate. Whereas in a self-hosted env the cluster is somehow configured to trust the issued token by the oidc provider (via pinniped), in managed clusters pinniped cannot perform this configuration.
As a result, the API server is no longer the entity to who we have to talk.

Pinniped is automatically detecting this scenario and in v0.7 it changes its internal behavior: now it deploys a LoadBalancer service, publicly reachable aimed at replacing the usual k8s API server: it is the `ImpersonationProxy`.

The typical Pinniped use case does require having an admin account in Kubectl for configuring everything. Under the hood, it looks for a  `CredentialIssuer` to determine how to proceed. So, assuming we are in the proper kubectl context, we can run:

```
pinniped get kubeconfig   --oidc-client-id my-client-id   --oidc-scopes openid,email   --oidc-listen-port 12345 --concierge-api-group-suffix pinniped.tmc.cloud.vmware.com
```
In a managed cluster, it will detect that a LoadBalancer has been deployed:

```
 "level"=0 "msg"="discovered CredentialIssuer"  "name"="pinniped-concierge-config"
 "level"=0 "msg"="discovered Concierge operating in impersonation proxy mode"  
 "level"=0 "msg"="discovered Concierge endpoint"  "endpoint"="https://IMPERSONATION_PROXY_URL"
 "level"=0 "msg"="discovered Concierge certificate authority bundle"  "roots"=1
 "level"=0 "msg"="discovered JWTAuthenticator"  "name"="jwt-authenticator"
 "level"=0 "msg"="discovered OIDC issuer"  "issuer"="MY_ISSUER"
 "level"=0 "msg"="discovered OIDC audience"  "audience"="CLIENT_ID"
 "level"=0 "msg"="discovered OIDC CA bundle"  "roots"=2
 "level"=0 "msg"="validated connection to the cluster"  
```

And will generate a kubeconfig like: 

```yaml
...
clusters:
- cluster:
    certificate-authority-data: <redacted> # CA of the **ImpersonationProxy, not the server* 
    server: https://IMPERSONATION_PROXY_URL
  name: pinniped
...
users:
- name: pinniped
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - oidc
      - --enable-concierge
      - --concierge-api-group-suffix=pinniped.tmc.cloud.vmware.com
      - --concierge-authenticator-name=jwt-authenticator
      - --concierge-authenticator-type=jwt
      - --concierge-endpoint=https://IMPERSONATION_PROXY_URL
      - --concierge-ca-bundle-data=<redacted>
      - --issuer=MY_ISSUER
      - --client-id=CLIENT_ID
      - --scopes=openid,email
      - --listen-port=12345
      - --ca-bundle-data=<redacted>
      - --request-audience=CLIENT_ID
      command: /usr/local/bin/pinniped
      env: []
      provideClusterInfo: true
```

So, first caveat: **how can we auto-discover the impersonation proxy URL without admin permissions?**
Ideas: 
1. suggest users adding a RBAC for `CredentialIssuer:get,list` permissions. This would require us implementing the aforementioned discovery in the kubeapps side (not -only- in the pinniped proxy, afaik, since we are talking to the API directly)
2. drop the discovery part for now and simply ask the users: are you using a managed environment? If so, please add the impersonation proxy URL instead of the usual k8s API server URL.

For the sake of simplicity, let's assume the 2nd option. That is, as an admin, I know I need to provide the impersonation URL (and its CA cert) in Kubeapps instead of the usual values.

## Using the impersonation proxy in Kubeapps

I've considered two main scenarios: 

### A) Single managed cluster (eg. AKS)

Supposing we want to configure Kubeapps with OIDC in a managed cluster some steps are required; namely:
1. Install Pinniped 0.7 as usual.
2. Create a jwt authenticator, as usual.
3. Get impersonation proxy IP:  `kubectl get svc -n vmware-system-tmc pinniped-concierge-impersonation-proxy-load-balancer -o jsonpath="{.status.loadBalancer.ingress[0].ip}"`
4. Get impersonation proxy CA: `kubectl get secret pinniped-concierge-impersonation-proxy-ca-certificate -n vmware-system-tmc -o jsonpath="{.data.ca\\.crt}"`
5. Configure Kubeapps values.yaml with this cluster config:

``` yaml
clusters:
- name: aks
  apiServiceURL: https://<IP> # impersonation proxy IP
  certificateAuthorityData: <redacted> #  impersonation proxy CA
  pinnipedConfig:
    enable: true
```

Problems so far: Kubeapps core (mainly Kubeops) is not fully prepared to use different k8s auth methods rather than inCluster when being configured as a single cluster.
Even if Kubeapps seems to work, it is not really usable. For instance:
![image](https://user-images.githubusercontent.com/11535726/115043494-d9d80380-9ed4-11eb-8acf-90cca6adf597.png)


### B) Usual self-managed cluster with multicluster using an additional managed cluster (eg. AKS)

(TBD)

Having already installed Pinniped in the additional (managed) cluster, is in the usual cluster in which Kubeapps is installed where we need to add the aforementioned `clusters:` excerp.
However, it seems I'm hitting a similar error as above... still investigating what's happening.

![image](https://user-images.githubusercontent.com/11535726/115050124-b82e4a80-9edb-11eb-8615-241970b7980c.png)


### Conclusions

- The discovery of the ImpersonationProxy cannot be performed automatically without the proper permissions (get/list credential issuer, afaik). Perhaps the best approach is just asking the users for entering the proper values.
- Currently, Kubeapps does not support a single-cluster installation with OIDC with the impersonation proxy. It is due to a set of in-cluster auth assumptions. Not sure what to do here, discussion required.

- Not really important but, anyway: if using TMC in the cluster with Kubeapps installed, the Pinniped API group suffixes and namespaces should also match. That is, simply installing Pinniped with `kubectl apply -f github.com/....` won't work. You will need to change it by the proper (TMC ones) suffixes and namespaces.

**Comment by absoludity** [comment] 2021-04-19 10:09
> Some updates so far (I'll be editing this comment to ad further details)

Thanks for the thorough communication @antgamdia . That's excellent work.

> ## New features in Pinniped
> 
> There is no new authentication mechanism (afaik), the key part is still based upon a `TokenCredentialRequest`, so the whole pinniped-proxy logic is still valid.

This was unexpected for me, but excellent! That makes this much less effort than I had anticipated.

> Pinniped is automatically detecting this scenario and in v0.7 it changes its internal behavior: now it deploys a LoadBalancer service, publicly reachable aimed at replacing the usual k8s API server: it is the `ImpersonationProxy`.
> 
> 
> So, first caveat: **how can we auto-discover the impersonation proxy URL without admin permissions?**
> Ideas:
> 
>     1. suggest users adding a RBAC for `CredentialIssuer:get,list` permissions. This would require us implementing the aforementioned discovery in the kubeapps side (not -only- in the pinniped proxy, afaik, since we are talking to the API directly)
> 
>     2. drop the discovery part for now and simply ask the users: are you using a managed environment? If so, please add the impersonation proxy URL instead of the usual k8s API server URL.
> 
> 
> For the sake of simplicity, let's assume the 2nd option. That is, as an admin, I know I need to provide the impersonation URL (and its CA cert) in Kubeapps instead of the usual values.

We should definitely do option 2 here IMO, as you've suggested. It makes sense that pinniped auto-detects this scenario as it writes the kubeconfig requested by the admin user. Kubeapps should simply be configured with the API server URL that is in the kubeconfig - I don't see any benefit to Kubeapps auto-detecting the K8s API service url that it should use (whether it's the impersonation proxy or the actual one).

> Problems so far: Kubeapps core (mainly Kubeops) is not fully prepared to use different k8s auth methods rather than inCluster when being configured as a single cluster.
> Even if Kubeapps seems to work, it is not really usable. For instance:
> ![image](https://user-images.githubusercontent.com/11535726/115043494-d9d80380-9ed4-11eb-8acf-90cca6adf597.png)

So this is interesting: when I [demo'd Kubeapps running in a TKG (1.1) management cluster](https://liveandletlearn.net/post/kubeapps-on-tkg-management-cluster/) I had this exact scenario, if I've understood correctly: Kubeapps was installed on the management cluster but was configured to deploy to the workload cluster(s) only (because TKG 1.1 didn't support OIDC for the management cluster, only the workload clusters). That is, it was configured with (both) clusters with explicit api urls and certs. So I'm keen to understand what changed that broke this (though I guess it's not surprising since we hadn't added CI tests). Note that the `inCluster` config is (from memory) only used to initialise the variable, I thought we overwrite the endpoint based on the config. Anyway, assuming this is reproducible, I agree it's an issue - let's create one :)


> ### B) Usual self-managed cluster with multicluster using an additional managed cluster (eg. AKS)
> 

> Now... **I'm able to install apps from our TMC cluster to AKS!**

Woohoo!


> ### Conclusions
> 
>     * Finally, **we are able to add additional (managed) clusters** so that Kubeapps can install apps there. However, we need to pass the impersonation proxy URL instead of the API server one.
>       
>       * The discovery of the ImpersonationProxy cannot be performed automatically without the proper permissions (get/list credential issuer, afaik). Perhaps the best approach is just asking the users for entering the proper values.

Agreed :)

> 
>     * Currently, Kubeapps **does not support a single-cluster installation with OIDC** with the impersonation proxy. It is due to a set of in-cluster auth assumptions. Not sure what to do here, discussion required.

As above, a surprise since we used this for the TKG demo, but something could have changed. Let's create an issue with steps to repro and fix it :)

> 
>     * Not really important but, anyway: if using TMC in the cluster with Kubeapps installed, the Pinniped API group suffixes and namespaces should also match. That is, simply installing Pinniped with `kubectl apply -f github.com/....` won't work. You will need to change it by the proper (TMC ones) suffixes and namespaces.

So if the cluster is being managed by TMC, I can't even install a separate pinniped version with the non-TMC api groups? Is that intentional do you know? I'd understood that the point was to be able to have multiple copies of pinniped running (using different api groups), but may have missed something.

Thanks again for the clear summary!

**Comment by antgamdia** [comment] 2021-04-19 15:41
> We should definitely do option 2 here IMO, as you've suggested. It makes sense that pinniped auto-detects this scenario as it writes the kubeconfig requested by the admin user. Kubeapps should simply be configured with the API server URL that is in the kubeconfig - I don't see any benefit to Kubeapps auto-detecting the K8s API service url that it should use (whether it's the impersonation proxy or the actual one).

Happy to see you also agree :) 

> So this is interesting: when I [demo'd Kubeapps running in a TKG (1.1) management cluster](https://liveandletlearn.net/post/kubeapps-on-tkg-management-cluster/) I had this exact scenario, if I've understood correctly: 
Kubeapps was installed on the management cluster but was configured to deploy to the workload cluster(s) only (because TKG 1.1 didn't support OIDC for the management cluster, only the workload clusters). 

> That is, it was configured with (both) clusters with explicit api urls and certs. So I'm keen to understand what changed that broke this (though I guess it's not surprising since we hadn't added CI tests). Note that the `inCluster` config is (from memory) only used to initialise the variable, I thought we overwrite the endpoint based on the config. Anyway, assuming this is reproducible, I agree it's an issue - let's create one :)

Yep, let me test it in both managed and self-managed clusters with odic, but I'm pretty sure it's an issue (my gut tells me it will appear just when using `pinnipedConfig.enable=true`).

> So if the cluster is being managed by TMC, I can't even install a separate pinniped version with the non-TMC api groups? Is that intentional do you know? I'd understood that the point was to be able to have multiple copies of pinniped running (using different api groups), but may have missed something.

No, it isn't what I meant. In TMC you can install multiple Pinniped versions with different API suffixes, But, supposing we already have a TMC-ready cluster running Kubeapps and we wanna add another additional cluster (not managed by TMC), we must use the same API group in both clusters (either the TMC or the default one). Since I chose the TMC one, I had to install Pinniped (in the additional cluster) with the same TMC API group. 

Thank you for taking a look at it and the friendly comments :) 

Let me close this issue in favor of #xxx and #xxx to track each matter separately.

**Closed by antgamdia** 2021-04-19 15:41 UTC
Labels: size/L

**Comment by absoludity** [comment] 2021-04-20 00:25
> No, it isn't what I meant. In TMC you can install multiple Pinniped versions with different API suffixes, But, supposing we already have a TMC-ready cluster running Kubeapps and we wanna add another additional cluster (not managed by TMC), we must use the same API group in both clusters (either the TMC or the default one). Since I chose the TMC one, I had to install Pinniped (in the additional cluster) with the same TMC API group.

Oh, in that case, yes, currently, though the longer-term solution will be to enable this as config for a cluster. It's very similar to the current situation with the pinniped namespace I think? In that, we've currently enabled a default pinniped namespace, which will be used by pinniped proxy, but are not yet using a per-cluster configuration even though a [per-cluster config can be set for namespace (and auth type and auth name](https://github.com/kubeapps/kubeapps/blob/master/pkg/kube/kube_handler.go#L85)). Currently pinniped itself [uses the default pinniped namespace from the env only](https://github.com/kubeapps/kubeapps/blob/master/cmd/pinniped-proxy/src/pinniped.rs#L242). Of course, with the api suffix we'll currently be limited to the two hard-coded suffixes, but it'd still be configurable per-cluster.

**Comment by antgamdia** [comment] 2021-04-20 09:04
> though the longer-term solution will be to enable this as config for a cluster.

Yes, I agree. This per-cluster approach would enable the authentication across different clusters running different Pinniped instances (with different API suffixes/namespaces). However, in the demo scenarios we are using, I don't think this situation really occurs (apart from a Pinniped version mismatch, since we are "living in the edge"). Anyway, let's file a new issue for that. It could be useful in the future.
