### ISSUE TITLE
When upgrading chart from kubeapps dashboard, chart version doesn't  match it's values.yaml

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubeapps/kubeapps#2658] opened 2021-04-09 02:16 UTC
### Description:
When upgrading chart from kubeapps dashboard, chart version doesn't match it's values.yaml

Details:
![image](https://user-images.githubusercontent.com/58658883/114118716-d6b0a680-991b-11eb-8b41-de6a50e420ed.png)

select a new version
![image](https://user-images.githubusercontent.com/58658883/114118717-d6b0a680-991b-11eb-8df7-bb8a536b4fc5.png)

I need manually click "restore defaults" to make the value correct.
![image](https://user-images.githubusercontent.com/58658883/114118797-0364be00-991c-11eb-84d8-f0ca920eb1f1.png)

### Describe the results you received:

chart's values.yaml dosen't change when selecting new version 

### Describe the results you expected:

chart's values.yaml match it's version

### Version of Helm, Kubeapps and Kubernetes:

```shell
kubernetes version v1.14.3
kubeapps image version 2.2.1
kubeapps chart version 5.3.0
```

Is this a bug in kubeapps 2? please help me with how to fix it, thanks.

**Comment by andresmgot** [comment] 2021-04-09 09:41
Hi @ZhangSIming-blyq,

There are two situations in which Kubeapps doesn't update a certain value when upgrading:

 - If you have modified the default value when first installing the chart, that value will be identified as "modified" and won't be updated to keep the user changes.
 - If, when upgrading, you modify any value before changing the version, that's identified as custom values so it won't be updated any more when changing versions.

If you are not modifying `Chart.appVersion` when installing the chart, nor you are changing anything in the values before selecting the latest version then yes, it can be a bug. Maybe it's related to the fact that the line has an inline-comment. Can you confirm that?

**Comment by ZhangSIming-blyq** [comment] 2021-04-09 09:56
> Hi @ZhangSIming-blyq,
> 
> There are two situations in which Kubeapps doesn't update a certain value when upgrading:
> 
> * If you have modified the default value when first installing the chart, that value will be identified as "modified" and won't be updated to keep the user changes.
> * If, when upgrading, you modify any value before changing the version, that's identified as custom values so it won't be updated any more when changing versions.
> 
> If you are not modifying `Chart.appVersion` when installing the chart, nor you are changing anything in the values before selecting the latest version then yes, it can be a bug. Maybe it's related to the fact that the line has an inline-comment. Can you confirm that?

So, if I want to make my manual change to a new version, what should I do?

**Comment by andresmgot** [comment] 2021-04-09 10:01
> So, if I want to make my manual change to a new version, what should I do?

First change the version, then modify the values you need. I know that the UX is not great there, we already have an open issue to address this: https://github.com/kubeapps/kubeapps/issues/1773

**Comment by ppbaena** [comment] 2021-04-26 09:55
Duplicate of #1773

**Closed by ppbaena** 2021-04-26 09:55 UTC
