### ISSUE TITLE
Cannot use latest Kubeapps release on TKG 1.3 cluster with identity management

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2764] opened 2021-05-06 03:51 UTC
### Description:

A vanilla TKG 1.3 cluster setup with identity management uses a version of Pinniped prior to a backwards incompatible change in Pinniped, for which Kubeapps has already updated. As a result, an older release of Kubeapps is required to work with the vanilla TKG 1.3 identity management.

### Steps to reproduce the issue:

1. Follow [TKG 1.3 setup to get workload clusters with identity management](https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13/)
2. Follow [Kubeapps on Tanzu Kubernetes Grid 1.3](https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13-part-2/)

### Describe the results you received:

Had to use an old version of Kubeapps to be compatible with Pinniped 0.4.1 which is (currently) used on the TKG 1.3 cluster, as well as a chart workaround to ensure the correct pinniped-proxy image was used (due to a bug in the chart which was subsequently fixed in a later Kubeapps version).

### Describe the results you expected:

Able to use the latest Kubeapps release.

### Additional information you deem important (e.g. issue happens only occasionally):

We need to find out:

- [ ] Will the version of Pinniped installed in TKG 1.3 be updated with a subsequent point-release, and if so, will it update to a version with the new cluster-scoped resources (ie. > 0.6.0).
- [ ] If not, we need to test whether we can simply install a newer Pinniped (multiple copies of pinniped are allowed) and recommend that, or
- [ ] we may also want to verify whether registering the cluster with TMC automatically installs the recent version and whether we can then use that with Kubeapps.

**Comment by antgamdia** [comment] 2021-05-18 23:21
Some updates here:

> Will the version of Pinniped installed in TKG 1.3 be updated with a subsequent point-release, and if so, will it update to a version with the new cluster-scoped resources (ie. > 0.6.0)

No, we cannot rely on that. We should assume that TKG will have Pinniped 0.4.1 in mid-term. We must seek other solutions in our end.

> If not, we need to test whether we can simply install a newer Pinniped (multiple copies of pinniped are allowed) and recommend that

Good* news here: pinniped pre 0.6 gets along with pinniped post 0.6 as long as they are in separate namespaces and they have different API suffixes.

I mean: I can confirm that the latest Kubeapps version is working on TKG 1.3 with Pinniped 0.8 while a Pinniped 0.4.1 is still running as a TKG addon.

*Caveat: if you remember (I didn't :P) we only support TWO specific API suffixes and namespaces.
So, either Pinniped is either:
- API suffix `*.pinniped-dev` in the namespace `pinniped-concierge`
- API suffix `*.pinniped.tmc.cloud.vmware.com` in the namespace `vmware-system-tmc`

>  we may also want to verify whether registering the cluster with TMC automatically installs the recent version and whether we can then use that with Kubeapps.

I haven't personally tested it with TKG 1.3, but I assume a similar behavior as in former tests. My guess is it will work because of my former comment, we do support the pinniped 'flavor' installed along with TMC.

Finally, I'm asking internally for more information about how to manually edit the TKG addons (for instance, for replacing it with a newer version). No updates here so far.


_Conclusion (regarding the documentation):_

- Although it's not the most elegant solution, we should (for now) instruct people to manually set the TMC Pinniped API suffix and namespaces.
  - But I'd also mention something like: skip this step if you are already using TMC
- Perhaps we should revisit the API suffixes thing in the Pinniped-Proxy again to use dynamic resources as you did for the new API (albeit I already tried it, but I didn't get it to work).

**Comment by absoludity** [comment] 2021-05-18 23:30
Excellent investigation and summary @antgamdia !

> * Although it's not the most elegant solution, we should (for now) instruct people to manually set the TMC Pinniped API suffix and namespaces.
>   
>   * But I'd also mention something like: skip this step if you are already using TMC

Yeah, at first I was thinking "what if they then want to make their cluster TMC managed". We may also want to mention that if they later add the cluster to TMC, they should delete this custom pinniped?

> 
> * Perhaps we should revisit the API suffixes thing in the Pinniped-Proxy again to use dynamic resources as you did for the new API (albeit I already tried it, but I didn't get it to work).

+1. I was thinking the same thing after using the dynamic resources in the apis service.

**Comment by antgamdia** [comment] 2021-05-24 15:12
Closing since we already did the investigation part. Let's track the required changes on the Pinniped-Proxy side at https://github.com/kubeapps/kubeapps/issues/2695

**Closed by antgamdia** 2021-05-24 15:12 UTC
Labels: component/auth, component/docs, kind/bug, priority/high, size/S
