### ISSUE TITLE
Upgrade with arguments

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#858] opened 2018-11-29 10:11 UTC
Some Charts require to run “helm upgrade” with some extra parameters:

 - The IP/Hostname in order to be configured properly. (see Ghost or Prestashop for instance).
 - Auto-generated passwords from databases or existing secrets (see WordPress)

The output of the “helm install” command shows the exact command the user should execute. This cannot be done from Kubeapps for now.

cc/ @juan131 @beltran-rubo

**Comment by prydonius** [comment] 2018-11-29 18:35
Hmm, I'm confused about the exact ask here, can't the IP/Hostname be configured using the values input when installing or upgrading? Are you saying that the user should be able to run the command listed in the NOTES.txt? That sounds a little like a dupe of #862?

**Comment by andresmgot** [comment] 2018-11-30 08:43
I think so. To obtain the hostname you need to execute a command (`kubectl get svc ...`) then with that result the user executes `helm upgrade --set hostname=...`.

I think that in our side, the easiest way to allow that is to allow users to detect what parameter is required and being able to get it from the UI. Then they can modify the values.yaml to set that resource. Probably we just need documentation specific for Kubeapps?

**Comment by beltran-rubo** [comment] 2018-11-30 08:59
Some of the apps require to be configured with the external IP/Hostname. They use that to create the links in the app itself.

For those apps, helm install command only deploys the database and they show the helm upgrade command the user has to use when k8s returns the specific IP/Hostname.

**Comment by prydonius** [comment] 2018-12-26 08:59
JSON schema could be used here to indicate which values are required when installing an app, however that then doesn't allow the flow where we allow the creation of the Service to generate a hostname that can be used on upgrade.

**Comment by prydonius** [comment] 2019-02-25 16:43
@beltran-rubo does the above make sense to you?

**Comment by cscazorla** [comment] 2019-10-21 10:11
We will tackle this issue at https://github.com/kubeapps/kubeapps/issues/1235

**Closed by cscazorla** 2019-10-21 10:11 UTC
Labels: awaiting-more-evidence
