### ISSUE TITLE
Application screen pagination

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2066] opened 2020-09-24 23:45 UTC
Hello
Using kubeapps helm chart version 4.0.0

When there are alot of applications, and I go to the application screen without filtering, it could get stuck for long time
Pagination would help a lot on this situation
What do you think ?

**Comment by absoludity** [comment] 2020-09-25 01:19
Yes, similar to #1010 for the catalog, we need to add pagination support, or better - dynamically loading the next results so it's still just scrolling, but either way ensuring we don't require loading all results when the page loads.

**Comment by absoludity** [comment] 2020-09-25 01:42
Actually, based on your other issue #2065 , I wonder if you're actually talking about the catalog, rather than the apps. Though it's relevant to both, it's more likely to be an issue with the catalog (and while testing the applications, I see the logos there are actually fetched from upstream, as opposed to the catalog where they're fetched internally.

**Comment by kfirfer** [comment] 2020-09-25 02:28
@absoludity 
even though there is caching , the browsers little struggled to render list of thouands of charts, it is also intensive for the server side

**Comment by absoludity** [comment] 2020-09-25 02:34
Yeah, totally agree. It's something we've wanted to do for a long time (see #1010) just hasn't yet been a priority since it works without.

**Comment by absoludity** [comment] 2020-09-29 06:43
Duplicate of #1010

**Closed by absoludity** 2020-09-29 06:43 UTC
