### ISSUE TITLE
Bug: Form "hidden" feature does not operate on default value

### ISSUE THREAD

**Issue by rarick** [kubeapps/kubeapps#1913] opened 2020-07-30 16:54 UTC
### Description:

I have the following scenario in my `values.schema.json`:

```
"dropdown": {
  "type": "string",
  "form": true,
  "default": "a",
  "enum": ["a", "b"]
},
"a": {
  "type": "string",
  "form": true,
  "hidden": {
    "path": "dropdown",
    "value": "b"
  }
},
"b": {
  "type": "string",
  "form": true,
  "hidden": {
    "path": "dropdown",
    "value": "a"
  }
}
```

### Describe the results you received:

When the form page is loaded, both `a` and `b` will **NOT** be hidden.

### Describe the results you expected:

I would expect `b` to be hidden, since the dropdown has a default value of `a`.  However, it does not appear that the form is recognizing the default value of this dropdown and marking `b` as hidden.

### Additional information you deem important (e.g. issue happens only occasionally):

I have not tested if this is solely an interaction that occurs with `enum`. It could possibly occur with other default values as well.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
CHART         	APP VERSION
kubeapps-3.7.2	v1.10.2    
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0+724e12f93f", GitCommit:"7207690010f08f2ae526ee3300d4a18ea65997fe", GitTreeState:"clean", BuildDate:"2020-01-06T18:32:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by batiati** [comment] 2020-07-30 17:40
Hi @rarick 
You're right, I can reproduce that, thank you for reporting.

A simple workarround for now is just set the same default value on values.json file.

**Comment by andresmgot** [comment] 2020-07-31 07:55
Marking this as a bug, thanks for reporting indeed.

**Comment by antgamdia** [comment] 2020-12-24 10:47
I've been trying to replicate this issue, but I wasn't fully able to.

In [schema.ts#L146](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/schema.ts#L146) we retrieve the value (from the values.yaml file) from a full path. With this value we evaluate the condition to decide whether or not the parameter should be hidden in [Param.tsx#L75](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Param.tsx#L75).

The main point is that the `values.yaml` should contain a value if `hidden.path` is specified in the `values.schema.json`. In the examples below,  `dropdown` and `secondLevelProperties/2dropdown` must exist and have a value so that [schema.ts#L146](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/schema.ts#L146) is not `undefined`.

Find below the example files and a GIF showing off my results. If it is -not- the desired behavior, please let me know

![issue1913](https://user-images.githubusercontent.com/11535726/103083269-481e5080-45dc-11eb-8e20-cc058d855459.gif)

values.yaml
```yaml
dropdown: a

secondLevelProperties:
  2dropdown: 2a
```

values.schema.json
```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "dropdown": {
      "type": "string",
      "form": true,
      "default": "a",
      "enum": [
        "a",
        "b"
      ]
    },
    "a": {
      "type": "string",
      "form": true,
      "hidden": {
        "path": "dropdown",
        "value": "b"
      }
    },
    "b": {
      "type": "string",
      "form": true,
      "hidden": {
        "path": "dropdown",
        "value": "a"
      }
    },
    "secondLevelProperties": {
      "type": "object",
      "title": "secondLevelProperties",
      "form": true,
      "properties": {
        "2dropdown": {
          "type": "string",
          "form": true,
          "default": "2a",
          "enum": [
            "2a",
            "2b"
          ]
        },
        "2a": {
          "type": "string",
          "form": true,
          "hidden": {
            "path": "secondLevelProperties/2dropdown",
            "value": "2b"
          }
        },
        "2b": {
          "type": "string",
          "form": true,
          "hidden": {
            "path": "secondLevelProperties/2dropdown",
            "value": "2a"
          }
        }
      }
    }
  }
}
```

**Comment by andresmgot** [comment] 2021-01-07 11:10
Yes @antgamdia, if the value is specified in the `values.yaml` the issue doesn't appear, the point is that since the `values.schema.json` already has a default value (`"default": "a",`) it shouldn't be needed to specify it in the values (and the hidden property should work).

I believe that the only thing that we need to do is to use the `param` value rather than obtaining it from the `appValues` (since the `param.value` already evaluates default values in the schema) so in the file you point (https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Param.tsx#L75) we would need to change it to something like:

```patch
  const evalCondition = (
    path: string,
    expectedValue?: any,
    paramDeploymentEvent?: DeploymentEvent,
  ): boolean => {
    if (paramDeploymentEvent == null) {
-      return getValue(appValues, path) === (expectedValue ?? true);
+      return param.value === (expectedValue ?? true);
    } else {
      return paramDeploymentEvent === deploymentEvent;
    }
  };
```

Since you already have a test setup, can you verify that @antgamdia?

**Comment by antgamdia** [comment] 2021-01-12 10:07
Thank you for the clarification; now I get the point of this issue. Sorry for the misunderstanding.
Unfortunately, I think your propsed change won't work as is (since `param.value` is `undefined`, see`"{"type":"string","form":true,"hidden":{"path":"dropdown","value":"a"},"path":"b"}"`) and we should check `param.hidden.value` instead.

I'm opening a PR addressing this issue.

**Closed** 2021-01-14 09:35 UTC
Labels: component/dashboard, help wanted, kind/bug, priority/high, size/S
