### ISSUE TITLE
Sorry! Something went wrong

### ISSUE THREAD

**Issue by dingzhixue** [kubeapps/kubeapps#2564] opened 2021-03-18 02:45 UTC
### Steps to reproduce the issue:

1. [First Step]
2. [Second Step]
3. [and so on...]

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by antgamdia** [comment] 2021-03-18 07:33
Could you please give us more information about your issue?

**Comment by andresmgot** [comment] 2021-03-18 08:24
Closing this issue as a duplicate of #2568

**Closed by andresmgot** 2021-03-18 08:24 UTC
