### ISSUE TITLE
Get "Something went wrong" after logged to dashboard

### ISSUE THREAD

**Issue by wwyhy** [kubeapps/kubeapps#1790] opened 2020-06-12 07:30 UTC
### Description:

I got the error "Something went wrong" after logged the dashboard.

### Steps to reproduce the issue:
following guide to install by helm chart 

### Describe the results you received:

![image](https://user-images.githubusercontent.com/83105/84476677-11788c80-acc1-11ea-80c5-59763fef4086.png)

### Describe the results you expected:

should be works, no error

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
[root@master kubeapps]# helm   --tiller-namespace kube-system version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

- Output of `helm list <kubeapps-release-name>`:

```
[root@master kubeapps]# helm   --tiller-namespace kube-system list
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Fri Jun 12 15:20:00 2020	DEPLOYED	kubeapps-3.7.1	v1.10.1    	kubeapps 
```

- Output of `kubectl version`:

```
[root@master kubeapps]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by absoludity** [comment] 2020-06-15 00:12
Duplicate of #1620

**Closed by absoludity** 2020-06-15 00:12 UTC
