### ISSUE TITLE
Can you support automatic creation of namespaces?

### ISSUE THREAD

**Issue by shibd** [kubeapps/kubeapps#712] opened 2018-10-09 06:29 UTC
If kubeapps cluster not namespace 'test',I use command `helm install --namespace=test mychart`,helm automatic create namespace 'test',Can you support this function on webpage?

**Comment by andresmgot** [comment] 2018-10-09 08:07
Yes, for achieving that you just need to write `test` in the `Namespace` box in the top bar.

I am going to close this as a duplicate of #613. Note that we plan to refactor this to achieve a better user experience in #598. Thanks for reporting! If you still have any question you can use any of those issues.

**Closed by andresmgot** 2018-10-09 08:07 UTC
