### ISSUE TITLE
Charts not removed from the database when a repository is deleted

### ISSUE THREAD

**Issue by m1small** [kubeapps/kubeapps#1033] opened 2019-05-16 22:28 UTC
Upon deleting a repo from Kubeapps the charts remain in the Catalog.  As an admin, I'd expect that deleting a repo would also remove the charts from the Catalog view.

**Comment by andresmgot** [comment] 2019-05-16 23:46
hi @m1small, I am not actually be able to reproduce the issue. A clean job must have been created to delete the database. Maybe what you saw was a bigger delay because the first time that you delete a repository it needs to pull the clean-up image.

Can you check if you can reproduce it with the latest versionof Kubeapps?

**Comment by andresmgot** [comment] 2019-06-17 13:39
@m1small let me close this issue since it's not possible to reproduce it, let me know if you still find this problem

**Closed by andresmgot** 2019-06-17 13:39 UTC
