### ISSUE TITLE
v3.7.4 create namespace failed, error message 405 Not Allowed

### ISSUE THREAD

**Issue by jamestung1990** [kubeapps/kubeapps#1895] opened 2020-07-28 03:34 UTC
### Steps to reproduce the issue:

1. Go namespace
2. Select create new
3. Type any namespace you want
4. Press create button

### Describe the results you received:

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

### Describe the results you expected:

Create namespace should work.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
kubeapps        kubeapps        2               2020-07-28 11:10:50.282994991 +0800 CST failed  kubeapps-3.7.4  v1.10.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment] 2020-07-28 05:32
Thanks for reporting @jamestung1990 . I've just tested locally and was unable to reproduce, but we'll check with the exact versions you've mentioned. What I see is what I'd expect: it works if I have RBAC to do so, otherwise I see an error like:

![create-namespace](https://user-images.githubusercontent.com/497518/88622829-f46c1180-d0e6-11ea-952e-3662eecea6f4.png)

In the mean-time, can you pls attach a screenshot of your browser with the debugger open, showing the 405 network request, as well as the output of ```kubectl -n kubeapps logs deployment/kubeapps nginx``` so we can see get more info regarding why nginx is resopnding with a 405. Thanks!

**Comment by absoludity** [comment] 2020-10-01 05:35
Closing due to a lack of info.

**Closed by absoludity** 2020-10-01 05:35 UTC
Labels: awaiting-more-evidence
