### ISSUE TITLE
syncer not using http proxy environment variables

### ISSUE THREAD

**Issue by r10r** [kubeapps/kubeapps#3263] opened 2021-08-12 14:45 UTC
Hi there,

I tried to deploy kubeapps  today using the latest helm chart:

```
kubeapps         	kubeapps 	1       	2021-08-12 16:05:22.038411956 +0200 CEST	deployed	kubeapps-7.2.1         	2.3.3   
```

But I struggled to get the syncer working behind a http proxy. I did set the following helm chart values:

```yaml
syncImage
  initialReposProxy:
    enabled: true 
    httpProxy: "http://proxy.company.de:3128"
    httpsProxy: "http://proxy.company.de:3128"
    noProxy: ".intern.company.de,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,localhost,100.64.0.0/10,.svc,.local,.example.com"
```

but the syncer jobs still fail with the following error:

```
[ruben@k8s-cluster9-controller kubeapps]$ k logs -n kubeapps pod/apprepo-kubeapps-sync-bitnami-m4vb6-phs9j
 38 time="2021-08-12T09:04:38Z" level=fatal msg="Get \"https://charts.bitnami.com/bitnami/index.yaml\": dial tcp 143.204.98.50:443: connect: connection refused"
```

## Solution

When trying to debug the issue I build and deployed a custom syncer image from https://github.com/kubeapps/kubeapps/commit/15cd52baec3f865027bc0663a4c9e81d275beb02
After that the syncer run was successful.

The syncer image in the chart version `kubeapps-7.2.1` is set to `bitnami/kubeapps-asset-syncer:2.3.3-scratch-r0`
Looking at the commit log I noticed that the http client changes that make use of the proxy environment variable (#3118) were added after v2.3.3 release.

So I think the syncer image should be updated to fix connection issues behind a http proxy.

**Comment by antgamdia** [comment] 2021-08-12 15:52
Hi, thanks a lot for reporting this issue and, especially, for pointing us out to the root cause. We will try to get it solved soon! 
cc @dlaloue-vmware

**Comment by antgamdia** [comment] 2021-09-15 12:08
Hi @r10r, I was quickly having a look at this issue (while solving another one). The unit tests are passing and everything looks good to me so far. I'm using the following values:
``` 
helm upgrade --install kubeapps bitnami/kubeapps -n kubeapps \ 
--set apprepository.initialReposProxy.enabled=true \
--set apprepository.initialReposProxy.httpProxy="http://localhost:8080" \ 
--set apprepository.initialReposProxy.httpsProxy="https://localhost:8080" \ 
--set apprepository.initialReposProxy.noProxy="http://example.com:8080"
```
>  Note that `initialReposProxy` is **not** under `syncImage`, as you indented in you example:
>> 
>>```yaml
>> syncImage:
>>  initialReposProxy:
>>    enabled: true
>>```  

The jobs are created with the proper environment variables

![image](https://user-images.githubusercontent.com/11535726/133430141-3c62d7c4-8a8f-4a6f-9158-b52d3340393a.png)

And, indeed, the proxy config is being set (in my case it is falling because I don't have any proxy, but it is trying to hit my 8080 port, as I set in the values)

```console
sync
time="2021-09-15T11:58:50Z" level=fatal msg="Get \"https://charts.bitnami.com/bitnami/index.yaml\": proxyconnect tcp: dial tcp [::1]:8080: connect: connection refused"
```

Let me close the issue, but please, reopen it if you find anything else.

**Closed as completed by antgamdia** 2021-09-15 12:08 UTC
Labels: kind/bug, component/asset-syncer, awaiting-more-evidence
