### ISSUE TITLE
An error occurred: Cannot read property 'map' of undefined.

### ISSUE THREAD

**Issue by yanruogu** [kubeapps/kubeapps#2956] opened 2021-06-08 08:25 UTC
### Description:

when I login to the kubeapps use kubernetes sa secrets， the error like this: 

![image](https://user-images.githubusercontent.com/5188514/121149702-78e5ff80-c875-11eb-8ca4-520741ad99a8.png)

I dont know what happend and how to fix this.

### Steps to reproduce the issue:

install step on this: 

 https://kubeapps.com/docs/getting-started/

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
# helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
# helm list -n kubeapps
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-06-08 15:45:50.840028641 +0800 CST	deployed	kubeapps-6.1.2	2.3.2
```

- Output of `kubectl version`:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yanruogu** [comment] 2021-06-08 09:03
when i open it with safari browser, the error like this: 

![image](https://user-images.githubusercontent.com/5188514/121156584-67075b00-c87b-11eb-9554-2fe6cf053227.png)

**Comment by antgamdia** [comment] 2021-06-08 15:43
Hi @yanruogu , thanks for using Kubeapps, I'm sorry you're running into this error. 
Unfortunately, I'm unable to reproduce it (I don't have a mac handy atm, though), but I've noticed you are using an old chart version. 

So, I first suggest you performing `helm repo update` to get the latest chart changes and then install Kubeapps again.

Anyway, could you please share another screenshot with the browser developer console to see the whole error there?

If the error persists using the latest chart version, I'd rather suggest using a different browser (just to discard a browser issue); in the meanwhile, I'll try to replicate the issue with Safari anyway.

**Comment by absoludity** [comment] 2021-06-09 00:06
Also, if you can let us know the role assigned to the service-account that you've used to login. Specifically, whether it can read namespaces (just in case we have a bug for certain situations where the authenticated user does not have access).

**Comment by yanruogu** [comment] 2021-06-09 06:14
I update the helm chart to version 7.1.0(kubeapps 2.3.2) and the problem is still the same.

the serviceaccount is kubeops-operator:

```
# kubectl get sa -n default |grep kubeapps-operator
kubeapps-operator                       1         22h

# kubectl  get clusterrolebinding -o yaml kubeapps-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-06-08T07:46:10Z"
  name: kubeapps-operator
  resourceVersion: "1068447347"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kubeapps-operator
  uid: 0a368dc1-594e-4f65-9392-959bcc630ed5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeapps-operator
  namespace: default
``` 


```
# kubectl get pods -n kubeapps
NAME                                                          READY   STATUS    RESTARTS   AGE
apprepo-kubeapps-sync-bitnami-8j5mn-9zzfg                     1/1     Running   2          3m28s
kubeapps-785fdbb589-vvmp2                                     1/1     Running   0          4m4s
kubeapps-785fdbb589-wb56z                                     1/1     Running   0          4m5s
kubeapps-internal-apprepository-controller-658485f7fd-lrnpx   1/1     Running   0          4m5s
kubeapps-internal-assetsvc-66d74f7b87-mrbvs                   1/1     Running   0          4m5s
kubeapps-internal-assetsvc-66d74f7b87-xbwxz                   1/1     Running   0          4m5s
kubeapps-internal-dashboard-857578c4f6-fk6qh                  1/1     Running   0          4m5s
kubeapps-internal-dashboard-857578c4f6-nk8xz                  1/1     Running   0          4m5s
kubeapps-internal-kubeops-6b6ddf6784-lfpqj                    1/1     Running   0          4m5s
kubeapps-internal-kubeops-6b6ddf6784-vgt6d                    1/1     Running   0          4m5s
kubeapps-postgresql-primary-0                                 1/1     Running   0          4m5s
kubeapps-postgresql-read-0                                    1/1     Running   0          4m5s
```

```
# kubectl get svc -n kubeapps
NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubeapps                       ClusterIP   10.254.92.193    <none>        80/TCP           4m9s
kubeapps-internal-assetsvc     ClusterIP   10.254.16.165    <none>        8080/TCP         4m9s
kubeapps-internal-dashboard    NodePort    10.254.142.85    <none>        8080:34501/TCP   4m9s
kubeapps-internal-kubeops      NodePort    10.254.225.176   <none>        8080:20539/TCP   4m10s
kubeapps-postgresql            ClusterIP   10.254.169.250   <none>        5432/TCP         4m9s
kubeapps-postgresql-headless   ClusterIP   None             <none>        5432/TCP         4m10s
kubeapps-postgresql-read       ClusterIP   10.254.225.9     <none>        5432/TCP         4m10s
```
I used NodePort to expose kubeops's port.  when I am trying to access the kubeops svc, I find a new error: 

```
#  curl http://10.1.56.114:20539/v1/clusters/default/releases
{"code":500,"message":"Kubernetes cluster unreachable: the server has asked for the client to provide credentials"}
```
Then I am trying to update the serviceaccount kubeapps-internal-kubeops's permission to cluster-admin , but the error is still the same.

**Comment by antgamdia** [comment] 2021-06-09 10:04
> I used NodePort to expose kubeops's port. when I am trying to access the kubeops svc, I find a new error:
> 
> ```
> #  curl http://10.1.56.114:20539/v1/clusters/default/releases
> {"code":500,"message":"Kubernetes cluster unreachable: the server has asked for the client to provide credentials"}
> ```
> 
> Then I am trying to update the serviceaccount kubeapps-internal-kubeops's permission to cluster-admin , but the error is still the same.

Well, this error is being thrown since you are not passing any Autho

**Comment by absoludity** [comment] 2021-06-09 23:46
Whatever the cause of the issue, we should not be assuming that [`namespaceList.namespaces` is always defined](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/actions/namespace.ts#L58), instead at least logging the non-error yet unexpected response if `namespaceList` doesn't have a `namespaces` property.

**Comment by antgamdia** [comment] 2021-06-11 10:45
Although I've been unable to replicate the error live, I've created a unit test for the `namespaceList` thing (see https://github.com/kubeapps/kubeapps/blob/v2.3.2/dashboard/src/actions/namespace.ts#L58). I'll send a PR fixing that bug soon. Thanks for reporting and helping Kubeapps improve :)

**Closed** 2021-06-15 09:47 UTC
Labels: component/dashboard, kind/bug, priority/medium, size/XS
