### ISSUE TITLE
Tiller proxy returning wrong release

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#765] opened 2018-10-24 10:34 UTC
It seems that Tiller-proxy instead of doing a full match with release name it is doing a sub-match.

This means that if for example I have `wordpress-miguel-1` and `wordpress-miguel-2`, when in the UI I access to `/apps/ns/miguel/wordpress-miguel-1` I will actually be retrieving wordpress-miguel-2`

**Comment by andresmgot** [comment] 2018-10-24 11:10
This is a duplicate of #756 (closing that one)

**Comment by prydonius** [comment] 2018-11-28 23:32
Closing as fixed

**Closed by prydonius** 2018-11-28 23:32 UTC
Labels: component/helm, milestone/1.0, priority/unbreak-now
