### ISSUE TITLE
corporate proxy

### ISSUE THREAD

**Issue by WillMoverley** [kubeapps/kubeapps#696] opened 2018-10-02 07:38 UTC
Hi,

My deployment of kubeapps is behind a proxy, so when the apprepo-sync pods come up, they cant get out, and terminate with Error.

time="2018-10-02T07:36:30Z" level=error msg="error requesting repo index" error="Get https://svc-catalog-charts.storage.googleapis.com/index.yaml: dial tcp: lookup svc-catalog-charts.storage.googleapis.com on 10.96.0.10:53: no such host" url="https://svc-catalog-charts.storage.googleapis.com/index.yaml"
time="2018-10-02T07:36:30Z" level=fatal msg="Can't add chart repository to database: Get https://svc-catalog-charts.storage.googleapis.com/index.yaml: dial tcp: lookup svc-catalog-charts.storage.googleapis.com on 10.96.0.10:53: no such host"

I have downloaded the Chart, and tried to add the Env variables in various places, but i cant seem to get it right.

Where/What can i modify to include http_proxy/https_proxy/no_proxy variables?

Many thanks,

**Comment by andresmgot** [comment] 2018-10-02 08:11
Hi @WillMoverley,

Unfortunately right now it's not possible to setup those `proxy` variables with the exiting Kubeapps chart. What you can do for the moment is to edit the different CronJobs that synchronizes the repositories and the `tiller-proxy` deployment (that will download and install the different charts) to include the environment variables that you need:

```
kubectl edit cronjob -n <release_namespace> apprepo-sync-bitnami
kubectl edit cronjob -n <release_namespace> apprepo-sync-incubator
kubectl edit cronjob -n <release_namespace> apprepo-sync-stable
kubectl edit cronjob -n <release_namespace> apprepo-sync-svc-cat
kubectl edit deployment -n <release_namespace> <release_name>-internal-tiller-proxy
```

When editing the different elements you need to add the required env vars:

```
        env:
        - name: http_proxy
          value: <proxy>
```

Let us know if that works for you.

Also note that you will lose those changes when upgrading Kubeapps.

**Comment by WillMoverley** [comment] 2018-10-02 09:33
Many thanks @andresmgot that did indeed work!

However i have set up an ingress, to the kubeapps-internal-dashboard service on port 8080, i get the web page no problem, but i can enter any random letters in the API token, and i get into the dashboard, with or without the right API token, i just get a swirling dot in the charts, and nothing seems to work! hmm

**Comment by andresmgot** [comment] 2018-10-02 09:53
You need to set up the ingress rule to point to the service `kubeapps` (port 80) instead of the internal one.

In any case, I will keep this issue open. We can make it easier for people to run Kubeapps behind a proxy.

**Comment by WillMoverley** [comment] 2018-10-02 10:01
Thanks again! 

this looks better, i cant just put anything in and access anymore, it does give me the

"There was an error connecting to the Kubernetes API. Please check that your token is valid."

However, when i enter a token for a cluster admin (that i use to get access to the kubernetes-dashboard for instance). i still get the above error.

**Comment by WillMoverley** [comment] 2018-10-02 10:36
its not related to the ingress though, as i get the same using the 
"kubectl port-forward -n kubeapps $POD_NAME 8080:8080" method too.

**Comment by WillMoverley** [comment] 2018-10-02 11:00
ok, update. by removing the proxy env vars from kubeapps-internal-tiller-proxy, i can login with my token, there must be something i need to no_proxy that the kubeapps-internal-tiller-proxy talks too.

**Comment by andresmgot** [comment] 2018-10-02 17:03
I see, yes, `tiller-proxy` needs to establish connections with the K8s API and Tiller but it doesn't need to contact the Internet (that's done in Tiller). You should be able to omit there all the vars.

Did you make it work?

**Comment by prydonius** [comment] 2018-10-02 18:11
@andresmgot actually doesn't tiller-proxy also need to download the chart to install to then send to Tiller?

**Comment by andresmgot** [comment] 2018-10-03 09:06
True, I got confused. Tiller-proxy needs to download the chart, that doesn't happen in Tiller.

**Comment by prydonius** [comment] 2018-10-04 00:35
Is there a way we can reproduce this setup so we can find a fix for this?

**Comment by WillMoverley** [comment] 2018-10-04 07:34
> @andresmgot actually doesn't tiller-proxy also need to download the chart to install to then send to Tiller? We might need to make sure somehow that tiller-proxy doesn't use the http_proxy env when connecting to Kubernetes or Tiller.

I just manually added tiller-deploy.kube-system to the no_proxy env on the kubeapps-internal-tiller-proxy deployment, not ideal to do manually as @andresmgot suggested above, due to upgrades/re-deployments etc. But it works for now at least!

```
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: http_proxy
          value: xxx.xxx.xxx.xxx:8080
        - name: https_proxy
          value: xxx.xxx.xxx.xxx:8080
        - name: no_proxy
          value: tiller-deploy.kube-system,10.96.0.1,localhost,127.0.0.0,127.0.1.1

```

**Comment by andresmgot** [comment] 2018-10-04 13:53
Glad to know! @prydonius @migmartri do you think it makes sense to expose environment variables for Kubeapps microservices from the chart? (To avoid having to re-patch running services after an upgrade).

**Comment by prydonius** [comment] 2018-10-04 23:15
Thanks @WillMoverley, glad that worked for you. @andresmgot is your question whether we should have a value to pass in arbitrary environment vars, or if we should have a special value for setting the http_proxy and https_proxy?

@WillMoverley are the extra values for no_proxy necessary? In particular, it would be difficult for us to get the pod IP, would just `tiller-deploy.kube-system,localhost,127.0.0.0,127.0.1.1` work?

**Comment by andresmgot** [comment] 2018-10-05 08:05
I mean arbitrary env vars

**Comment by WillMoverley** [comment] 2018-10-05 08:08
> Thanks @WillMoverley, glad that worked for you. @andresmgot is your question whether we should have a value to pass in arbitrary environment vars, or if we should have a special value for setting the http_proxy and https_proxy?
> 
> @WillMoverley are the extra values for no_proxy necessary? In particular, it would be difficult for us to get the pod IP, would just `tiller-deploy.kube-system,localhost,127.0.0.0,127.0.1.1` work?

Hey

I cant remember which deployment i added the env var's to complained about communicating with the pod IP, but one of them did for sure, ill do some testing and remove it, and get back to you!

**Comment by PingPongBalls** [comment] 2018-10-16 07:33
is anyone got the similar issue i got?
i have setup the proxy and no_proxy for  "kubeapps-internal-tiller-proxy deployment",
but getting this from the pod's log:

i am getting this error from kubeapps frontend.

```
time="2018-10-16T07:08:52Z" level=info msg="Using tiller host: tiller-deploy.kube-system:44134"
time="2018-10-16T07:08:52Z" level=info msg="Started Tiller Proxy" addr=":8080"
[negroni] 2018-10-16T07:09:56Z | 401 | 	 1m15.012306003s | kubeapps-internal-tiller-proxy:8080 | POST /v1/namespaces/default/releases 
[negroni] 2018-10-16T07:11:26Z | 401 | 	 1m15.015368583s | kubeapps-internal-tiller-proxy:8080 | POST /v1/namespaces/default/releases
```
if i did not setup the proxy,
the code will be 500 instead of 401.

using kubeapps dashboard chart version 0.6.2, helm 2.11

**Comment by andresmgot** [comment] 2018-10-16 13:54
Hi @PingPongBalls, it seems that you are not using a token to authenticate against the cluster. How are you accessing the service? The dashboard web interface should ask you to introduce that token.

**Comment by PingPongBalls** [comment] 2018-10-17 00:41
without the proxy i am actually closer in fact, but when i try to install the app, it did not work:

```
[negroni] 2018-10-17T00:36:07Z | 200 | 	 19.863179ms | kubeapps-internal-tiller-proxy:8080 | GET /v1/namespaces/default/releases 
[negroni] 2018-10-17T00:36:14Z | 200 | 	 9.027981ms | kubeapps-internal-tiller-proxy:8080 | GET /v1/namespaces/default/releases 
[negroni] 2018-10-17T00:36:14Z | 200 | 	 6.49876ms | kubeapps-internal-tiller-proxy:8080 | GET /v1/namespaces/default/releases 
[negroni] 2018-10-17T00:36:24Z | 200 | 	 15.662953ms | kubeapps-internal-tiller-proxy:8080 | GET /v1/releases 
[negroni] 2018-10-17T00:36:39Z | 200 | 	 13.860935ms | kubeapps-internal-tiller-proxy:8080 | GET /v1/releases 
time="2018-10-17T00:37:46Z" level=info msg="Creating Helm Release"
2018/10/17 00:37:46 Downloading repo https://charts.bitnami.com/bitnami/index.yaml index...
[negroni] 2018-10-17T00:37:46Z | 500 | 	 44.85499ms | kubeapps-internal-tiller-proxy:8080 | POST /v1/namespaces/default/releases
```

**Comment by andresmgot** [comment] 2018-10-17 08:33
Maybe @WillMoverley can clarify which settings worked for him.

What I think it may happen is that you need to add to the `no_proxy` list the hostname of the kubernetes service. I see that you are setting a range for that: `10.65.0.0/16`, is that correct? That hostname is available in the env var `KUBERNETES_SERVICE_HOST` within the pod.

**Comment by prydonius** [comment] 2019-01-24 18:32
For reference, the DefaultTransport (search in here https://golang.org/pkg/net/http/) sets `http.ProxyFromEnvironment` for the `Proxy`, and the `http.ProxyFromEnvironment` function (https://golang.org/pkg/net/http/#ProxyFromEnvironment) handles the case where no proxy is defined in the environment.

**Comment by flofourcade** [comment] 2019-07-26 14:56
Hi,

Facing the same issue.

The sync jobs work, but tiller proxy can't download chart from remote repository.

To make it work, I had to change https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go the same way @ralfv did with monocular/cmd/chart-repo/utils.go (func initNetClient).
I rebuilt the tiller proxy image.

Then I patch the env of my tiller-proxy containers with the following values:
```yaml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: http_proxy
          value: my_proxy_ip:my_proxy_port
        - name: no_proxy
          value: localhost,127.0.0.1,10.96.0.1,tiller-deploy.kube-system,kubernetes
```
And it works. Remote repositories are synced, and I can deploy / upgrade charts in my cluster

**Comment by andresmgot** [comment] 2019-07-29 06:57
Hi @flofourcade,

Thank you for posting your fix. In theory it should work by default if you just modify the environment variables. Did you try setting the environment variables before changing the code?

**Comment by flofourcade** [comment] 2019-07-29 07:32
No, it won't work for me just with the env vars in v2.0.1. I can see in tiller-proxy container log  it get stuck on
`
Downloading repo https://xxx.xxx/xxx/index.yaml index...
`
I tried setting http_proxy/https_proxy/no_proxy/HTTP_PROXY/HTTPS_PROXY with many different values.
So I had a look at the code and I saw that tiller proxy uses 
```go
chartUtils "github.com/kubeapps/kubeapps/pkg/chart"
```
to download index and charts from remote repositories.
In https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go, the func InitNetClient looks like this : 
```go
func (c *Chart) InitNetClient(customCA *CustomCA) (HTTPClient, error) {
...
// Return Transport for testing purposes
	return &clientWithDefaultUserAgent{
		client: &http.Client{
			Timeout: time.Second * defaultTimeoutSeconds,
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{
					RootCAs: caCertPool,
				},
			},
		},
		userAgent: c.userAgent,
	}, nil
}
```
The net client defines au custom transport, so it don't use proxy settings from env vars.
Adding 
```go
Proxy: http.ProxyFromEnvironment,
```
did the job.Env vars are now taken into account.

**Comment by andresmgot** [comment] 2019-07-29 08:33
:+1: it just seemed weird that that was not reported/fixed before. Do you mind sending a PR for this?

**Comment by flofourcade** [comment] 2019-07-29 08:42
I forked the repo. I'll send a PR ASAP.

**Closed** 2019-07-30 08:48 UTC
Labels: component/chart-repo, component/helm, help wanted, priority/low
