### ISSUE TITLE
Latest release of Kubeapps is not working on AKS

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#355] opened 2018-06-08 11:06 UTC
Steps to reproduce:

* Get Kubeapps v1.0.0-alpha.3
* Deploy in a newly created AKS cluster
* Open the dashboard
* Try to deploy an app

Expected results:

* The app details view appears successfully

Actual results:

* The view doesn't appear as it seems to be getting on a loop to get the tiller config maps. This is the networking activity:

![screen shot 2018-06-08 at 1 05 47 pm](https://user-images.githubusercontent.com/925437/41155063-b4cab798-6b1c-11e8-8e72-c792516b34a9.png)

After several calls, it gets a 401 on ```http://localhost:56158/api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name=test-aerospike-mesh```

**Comment by prydonius** [comment] 2018-06-08 21:08
I believe the issue is related to the recent update to Helm CRD which changes the way release are named. If you have an older version of the Helm CRD controller, but a newer version of the dashboard, the dashboard will look for a Tiller release called `redis` whilst the Helm CRD controller will create `$NAMESPACE-redis`. If you built from master, what is the output of `cat static/kubeapps-objs.yaml | grep image:`?

From what you mentioned to me in Slack, it sounds like you tried this first on master and then tried the v1.0.0-alpha.3 release. Did you delete the HelmRelease you created from master before you switched to that release? I wasn't able to reproduce this with the v1.0.0-alpha.3 release in my AKS cluster.

I am surprised you're getting to the services call, that to me implies that it was actually able to find the Helm Release in the end... what is the full URL of the configmap request? Does the one just before the websocket return anything? Also strange is the 401, I'm not able to reproduce that either on v1.0.0-alpha.3, my websocket calls go through successfully.

**Comment by prydonius** [comment] 2018-06-08 21:11
I have tested both on Firefox and Chrome and I'm not able to reproduce on v1.0.0-alpha.3.

@sameersbn @andresmgot can you also try to reproduce the issue?

**Comment by prydonius** [comment] 2018-06-08 23:10
Ok I tried to reproduce on a new AKS cluster I just launched, and now I'm seeing some issues.

Firstly, the Helm CRD controller seemed to have issues when starting up but is running fine after a while:

```
k logs -f tiller-deploy-544497fcfc-2x7fw -n kubeapps -c controller                                                                                                                                                                                                                                                        16:05    06.08.18
2018/06/08 22:48:00 Using tiller host: localhost:44134
2018/06/08 22:48:00 Starting HelmReleases controller
2018/06/08 22:48:00 Cache synchronised, starting main loop
ERROR: logging before flag.Parse: W0608 22:49:00.823443       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:50:01.894229       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:51:02.917359       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:52:03.951854       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:53:04.989588       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:54:06.019735       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:55:07.043950       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:56:08.071460       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:57:09.111412       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:58:10.144522       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 22:59:11.184312       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:00:12.217578       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:01:13.245102       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:02:14.278227       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:03:15.301392       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:04:16.326835       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: W0608 23:05:53.297906       1 reflector.go:334] github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: watch of *v1.HelmRelease ended with: very short watch: github.com/bitnami-labs/helm-crd/cmd/controller/controller.go:125: Unexpected watch close - watch lasted less than a second and no items received
2018/06/08 23:05:54 Downloading repo https://kubernetes-charts.storage.googleapis.com/index.yaml index...
2018/06/08 23:05:55 Downloading https://kubernetes-charts.storage.googleapis.com/aerospike-0.1.7.tgz ...
2018/06/08 23:05:55 Installing release default-test into namespace default
2018/06/08 23:05:56 Installed/updated release default-test (status DEPLOYED)
```

The other issue I'm seeing is that my websocket requests are now also failing with a 401.

**Comment by prydonius** [comment] 2018-06-09 00:12
I've been digging into this a bit more and it appears that on AKS, traffic is routed through an `azureproxy` nginx deployment in the `kube-system` namespace. The configuration for this can be found in the configmap `azureproxy-config`. Notably, it's missing configuration we needed to add to our nginx proxy to ensure WebSocket connections can go through correct: https://github.com/kubeapps/kubeapps/blob/master/manifests/nginx-vhost.conf#L7.

I'm not 100% if this is the actual cause, but it is possible. Viewing the logs of the `azureproxy` pod I am able to see the requests for the Kubernetes API from Kubeapps going through it.

```
$ kubectl logs -n kube-system -f --tail 1 azureproxy-79c5db744-hfs6x | grep Chrome
10.244.2.6 - - [09/Jun/2018:00:09:49 +0000] "GET /apis/helm.bitnami.com/v1/namespaces/default/helmreleases/test HTTP/1.0" 200 2874 "http://localhost:5000/apps/ns/default/default-test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
10.244.2.6 - - [09/Jun/2018:00:09:49 +0000] "GET /api/v1/namespaces HTTP/1.0" 200 3462 "http://localhost:5000/apps/ns/default/default-test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
10.244.2.6 - - [09/Jun/2018:00:09:49 +0000] "GET /api/v1/namespaces/kubeapps/configmaps?labelSelector=NAME%20in%20(default-test) HTTP/1.0" 200 52535 "http://localhost:5000/apps/ns/default/default-test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
10.244.2.6 - - [09/Jun/2018:00:09:50 +0000] "GET /api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Ddefault-test-aerospike-mesh HTTP/1.0" 401 165 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
10.244.2.6 - - [09/Jun/2018:00:09:51 +0000] "GET /api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Ddefault-test-aerospike HTTP/1.0" 401 165 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
```

I don't understand why my previous cluster did not have this issue, I've already deleted it so I cannot check if it also had the azureproxy.

cc @ritazh

**Comment by prydonius** [comment] 2018-06-09 01:04
Okay, I am now convinced that the problem is that the `azureproxy-config` is missing the WebSocket upgrade configuration. In AKS, the `kubernetes.default` service somehow routes to the `azureproxy` deployment in the `kube-system` namespace. The Kubeapps api gateway routes to `kubernetes.default` (https://github.com/kubeapps/kubeapps/blob/master/manifests/nginx-vhost.conf#L17) and azureproxy reverse proxies the request to the AKS DNS hostname (e.g., something like `https://<AKS_HOSTNAME>.hcp.eastus.azmk8s.io`). If I update the `kubeapps-vhost` configuration to proxy directly to `https://<AKS_HOSTNAME>.hcp.eastus.azmk8s.io` instead of `kubernetes.default`, the WebSocket connections work. This is again because our Kubeapps vhost correctly forwards WebSocket connections.

Because the `azureproxy` does not forward WebSocket connections correctly, the request is treated as an HTTP request and the WebSocket protocol we send (https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/Auth.ts#L19) is not read and instead the API server is looking for an `Authorization` header to authenticate the request. WebSocket connections from the browser do not forward the `Authorization` header, so the API server responds with a 401.

If the `azureproxy` forwards WebSocket connections correct, the API server will look for the bearer token in the WebSocket protocol. I'm not able to fully verify this as I'm unable to make changes to the `azureproxy-config` ConfigMap, I believe this ConfigMap and the `azureproxy` Deployment are being managed by the kubelet and any changes are reverted after a small amount of time. The only way to test this would be to change the configuration on the master node, which is not possible in AKS.

**Comment by prydonius** [comment] 2018-06-09 01:14
I added a comment in https://github.com/Azure/AKS/issues/408#issuecomment-395928798 to put this issue on the AKS team's radar.

**Comment by olegchorny** [comment] 2018-06-09 20:15
I have the same issue with custom controller, without azure-proxy it works good, but now, seems like after AKS started to use azure-proxy, my operator getting such errors:
 _watch  ended with: very short watch: controller.go: Unexpected watch close - watch lasted less than a second and no items received_

**Comment by prydonius** [comment] 2018-06-11 18:32
@olegchorny thanks, yeah seems like the new azureproxy is certainly the issue here! Hopefully this gets fixed on the AKS side soon!

**Comment by prydonius** [comment] 2018-06-11 21:04
Here is the workaround for Kubeapps on AKS. As described above, this modified the Kubeapps' frontend nginx configuration to point directly to the AKS master hostname instead of pointing to `kubernetes.default`. Note that although this fixes WebSocket requests from the UI, the controllers still experience the "unexpected watch close" errors described above. This has the controller reconnecting, and upgrading Helm Charts and re-syncing chart repos every few seconds - which is obviously not ideal.

1. Ensure that your cluster is using azureproxy, if it isn't you don't need this fix:
    ```
    kubectl get deploy -n kube-system azureproxy
    ```
1. If the above command returned a result, execute the following patch:

    ```
    MASTER_HOST=$(kubectl get cm -n kube-system -o yaml azureproxy-config | grep 'server .*;$' | sed 's/\ *server \(.*\):443;/\1/') kubectl get cm -n kubeapps -l=app=kubeapps -o yaml | sed "s/kubernetes.default/$MASTER_HOST/" | kubectl apply -f - && kubectl delete po -n kubeapps -l app=kubeapps
    ```
1. Wait for the `kubeapps` frontend to be ready:

    ```
    kubectl get po -n kubeapps -l app=kubeapps -w
    ```
    
1. Reopen the dashboard
    ```
    kubeapps dashboard
    ```

**Comment by tomconte** [comment] 2018-06-22 07:48
Per AKS issue https://github.com/Azure/AKS/issues/408, this should now be fixed for all newly created clusters. Many thanks for your research and feedback!

**Comment by prydonius** [comment] 2018-06-22 18:03
Thanks @tomconte, happy to help and glad to see the issue fixed!

**Closed by prydonius** 2018-06-22 18:03 UTC
Labels: kind/bug, priority/critical-urgent
