### ISSUE TITLE
Bitnami Redis chart causes JS Error

### ISSUE THREAD

**Issue by plnordquist** [kubeapps/kubeapps#1695] opened 2020-04-24 22:32 UTC
### Description:

I've deployed the redis chart from the Bitnami charts repository at https://charts.bitnami.com/bitnami and when I try to view the deployed instance in Kubeapps it causes a type error in the Chrome console and Kubeapps pops up a page that says `Sorry! Something went wrong.`

### Steps to reproduce the issue:

1. Deploy redis chart from bitnami charts repo
2. Attempt to view the deployed redis chart
3. Kubeapps UI fails to render the output

### Describe the results you received:

Failed to view deployed chart

### Describe the results you expected:

View the deployed chart

### Additional information you deem important (e.g. issue happens only occasionally):

I'm running a devel version of kubeapps since I'm creating a PR for modifying some OAuth URI variables in the dashboard config.
- Console Error:
```
TypeError: Cannot read property 'type' of undefined
    at t.b (ServiceItem.tsx:41)
    at Yo (react-dom.production.min.js:153)
    at ys (react-dom.production.min.js:261)
    at yu (react-dom.production.min.js:246)
    at vu (react-dom.production.min.js:246)
    at uu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wi (react-dom.production.min.js:122)
    at Ki (react-dom.production.min.js:123)
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        services        91              2020-04-24 14:20:31.165057811 -0700 PDT deployed        kubeapps-3.5.3  DEVEL
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment] 2020-04-27 02:57
Thanks @plnordquist . This is, I think, a duplicate of #1620 which we'll fix ASAP. I'll close this as a duplicate, but feel free to re-open if you think it is different.

**Comment by absoludity** [comment] 2020-04-27 03:24
Actually, re-opening, as it's different: The error reported in the console is that a (service) resource doesn't have a spec. Looking at the templates of the bitnami redis chart, this should never be the case (not that Kubeapps should error like this as a result of a bad template - that should still be fixed), but after a brief attempt to reproduce the issue, I'm unable to do so.

Peter, do you know if there was anything more specific that you did? I tried installing Redis with the defaults, then without the slave, then manually setting slaves to zero, but in every case, I could view the deployment without issue?

**Comment by plnordquist** [comment] 2020-04-27 16:18
Sorry I probably should have included the values I used in the first post.  Here's the values I used:

```
slaveCount: 3
networkPolicy:
  enabled: true
metrics:
  enabled: true
password: "<redis-password>"
global:
  storageClass: "<storage-class-name>"
serviceAccount:
  create: true
```

**Comment by andresmgot** [comment] 2020-04-28 09:20
Hi @plnordquist,

I am not able to reproduce it either with your values:

![Peek 2020-04-28 11-16](https://user-images.githubusercontent.com/4025665/80470063-c0dfe680-8941-11ea-927a-2a90a0b6b611.gif)

From your original post, I see that you are using the development version of Kubeapps:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        services        91              2020-04-24 14:20:31.165057811 -0700 PDT deployed        kubeapps-3.5.3  DEVEL
```

This version is meant to be used only for development purposes and maybe there is some image in your deployment in a inconsistent state. I recommend you to use the latest release from the bitnami repository:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install kubeapps --namespace kubeapps bitnami/kubeapps --set useHelm3=true
```

Can you verify if installing the latest stable version helps with your issue?

**Comment by plnordquist** [comment] 2020-04-28 17:09
I think I figured this one out with a few breakpoints.  I setup a namespace named `services` for kubeapps and the redis cluster for oauth2-proxy.  It's treating a secret from the redis deployment as a service resource due to the presence of the `services` namespace in the selfLink in this matcher https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.tsx#L96.  I see a comment there that it's not using the kind since it's in a list, in my version of k8s I'm able to use kubectl to get services and get secrets and I can see the kind in each item and the kind List of the wrapper.  Was there a version of k8s that didn't provide the kind on each item?

**Comment by andresmgot** [comment] 2020-04-29 08:48
ahh, I see the bug, yes since the namespace is called `services` it's detecting secrets as services and since they don't have the expected info it crashes. I will send a PR fixing this so we are only taking the interesting piece of the path.

**Closed** 2020-05-13 10:49 UTC
Labels: kind/bug
