### ISSUE TITLE
Unable to switch between clusters in kubeapps multi clusters configuration

### ISSUE THREAD

**Issue by banicr** [kubeapps/kubeapps#3256] opened 2021-08-11 15:45 UTC
### Description:

Once kubeapps installation is successful and kubeapps page opens, I can see all the attached clusters in the clusters list, but I can’t  switch to other clusters it throws 401 or similar error.

### Steps to reproduce the issue:

1. Configured the OIDC provider (CSP)
2. Installed the nginx-ingress controller
3. Installed the cert-manger and ClusterIssuer
4. Created the custom values.yaml file and added the contents related to my environment. (for multi cluster added apiServiceURL, CertificateAuthorityData and ServiceToken).
5. Installed the kubeapps using the custom values.yaml file
6. Configured Rbac

### Describe the results you received:

Can not switch to other clusters and gets 401 error

### Describe the results you expected:

Should be able to switch between clusters

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-08-11 15:38:38.46883253 +0000 UTC	deployed	kubeapps-7.2.1	2.3.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+vmware.1", GitCommit:"c1a2f0ee316b35eca4ef6a7cb15ec9cc31a13f8f", GitTreeState:"clean", BuildDate:"2021-05-24T18:38:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment] 2021-08-16 04:22
Here's what I wrote in our email exchange:

> If the user can login and view the default cluster yet see a 401 when switching to a different cluster, this then means that the *same* request which Kubeapps sent to the default cluster (ie. a simple request with the authentication token), fails for the other clusters. Assuming that you've installed the same pinniped jwt-authenticator on those other clusters (with the same pinniped version) as per your confluence page, I would think that again the logs of pinniped-proxy when this happens would be most useful. If you can reproduce this issue, grab the logs from the pinniped-proxy pod (remove any private data) and create an issue on our Github project, we can investigate this one also. In fact, I wonder if this is the same issue as 1. above (ie. if you check the request in the browser debugger, does it also say "failed to exchange credentials"? Anyway, please include all the detail on the Github issue.

So thanks for creating the issue, when you get a chance, please attach the logs of the pinniped-proxy pod (after removing any private data) so we can investigate further. As mentioned above, I suspect this is the same issue as #3255 , but the data will tell :)

**Comment by absoludity** [comment] 2021-09-23 00:43
Logs of pinniped-proxy provided by @banicr 
```
 ERROR kube::client            > failed with error error trying to connect: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:67:, error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:588:, error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:../crypto/asn1/a_verify.c:170:, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1915: (certificate signature failure) 
 ERROR pinniped_proxy::service > Failed to exchange credentials

Caused by:
    err creating token exchange: "{\"apiVersion\":\"login.concierge.pinniped.tmc.cloud.vmware.com/v1alpha1\",\"kind\":\"TokenCredentialRequest\",\"metadata\":{\"name\":\"\",\"namespace\":\"vmware-system-tmc\"},\"spec\":{\"token\":\"...redacted...\",\"authenticator\":{\"apiGroup\":\"authentication.concierge.pinniped.tmc.cloud.vmware.com\",\"kind\":\"JWTAuthenticator\",\"name\":\"kubeapps-jwt-authenticator\"}},\"status\":null}"
    HyperError: error trying to connect: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:67:, error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:588:, error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:../crypto/asn1/a_verify.c:170:, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1915: (certificate signature failure)
```

As suspected, the logs here (together with a screenshot that can't be posted here) show that when switching to another cluster, the Kubeapps service (pinniped-proxy) was unable to verify the tls certificate provided by the other cluster. This means the configured `certificateAuthorityData` is not able to be used to verify the certificate.

Checking that data (provided by @banicr - thanks) shows that the issue is the data has been double-base64 encoded. For example, after saving the `certificateAuthorityData` for the other cluster from the config into a bash environment variable, I can only view the certificate by applying a base64 decode twice:

```
echo $certData | base64 -d | base64 -d
-----BEGIN CERTIFICATE-----
...redacted...
-----END CERTIFICATE-----
```

The [instructions in our docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/deploying-to-multiple-clusters.md#a-kubeapps-configuration-example) mention that the certificate must be base64 encode, but also that you can grab this base64 encoded data directly from your kubeconfig file for the cluster. It looks like this method has been used, but then additionally base64 encoded.

@banicr Can you please confirm that if you update your config so that the `certificateAuthorityData` for your additional clusters is only base64 encoded once rather than twice, that this fixes your issue? I'll close it here, but please re-open it if it does not. (Note that you may need to delete pods as changing a config map doesn't cause pods which use that config map to be restarted).

**Closed by absoludity** 2021-09-23 00:43 UTC
Labels: awaiting-more-evidence, component/project
