### ISSUE TITLE
ERROR:  relation "files" does not exist at character 34

### ISSUE THREAD

**Issue by chinaboy007** [kubeapps/kubeapps#2188] opened 2020-11-26 13:30 UTC
**#helm version**
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**#helm search repo kubeapps**
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/kubeapps        5.0.0           2.0.1           Kubeapps is a dashboard for your Kubernetes clu...

**#kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps**
2020-11-26 13:20:33.061 GMT [278] STATEMENT:  
                SELECT EXISTS(
                        SELECT 1 FROM files
                        WHERE chart_files_id = $1 AND
                                repo_name = $2 AND
                                repo_namespace = $3 AND
                                info ->> 'Digest' = $4
                        )
2020-11-26 13:20:33.358 GMT [262] ERROR:  relation "files" does not exist at character 13
2020-11-26 13:20:33.358 GMT [262] STATEMENT:  INSERT INTO files (chart_id, repo_name, repo_namespace, chart_files_ID, info)
                VALUES ($1, $2, $3, $4, $5)
                ON CONFLICT (repo_namespace, chart_files_ID)
                DO UPDATE SET info = $5

2020-11-26 13:20:33.358 GMT [278] ERROR:  relation "files" does not exist at character 34
2020-11-26 13:20:33.358 GMT [278] STATEMENT:  
                SELECT EXISTS(
                        SELECT 1 FROM files
                        WHERE chart_files_id = $1 AND
                                repo_name = $2 AND
                                repo_namespace = $3 AND
                                info ->> 'Digest' = $4
                        )
2020-11-26 13:20:33.617 GMT [262] ERROR:  relation "files" does not exist at character 13
2020-11-26 13:20:33.617 GMT [262] STATEMENT:  INSERT INTO files (chart_id, repo_name, repo_namespace, chart_files_ID, info)

**Comment by antgamdia** [comment] 2020-11-26 13:34
Thank you for letting us know about this error. Unfortunately, we would need a little bit more context to replicate and solve it.
Which actions were you performing before you got this trace?

**Comment by chinaboy007** [comment] 2020-11-26 13:45
**helm install kubeapps . -f values.yaml -n webapps**

**kubectl get kubeapps -n webapps**
kubeapps-8bfc5c985-b8gtb                                     1/1     Running   0          32m
kubeapps-8bfc5c985-xf795                                     1/1     Running   0          32m
kubeapps-internal-apprepository-controller-f9bfc5b8b-h4sdl   1/1     Running   0          35m
kubeapps-internal-assetsvc-69f67698d5-5qwsd                  1/1     Running   0          35m
kubeapps-internal-assetsvc-69f67698d5-kbrxs                  1/1     Running   0          35m
kubeapps-internal-dashboard-f5bb54785-6tr2d                  1/1     Running   0          24m
kubeapps-internal-dashboard-f5bb54785-8k6zr                  1/1     Running   0          24m
kubeapps-internal-kubeops-5b44cc69c6-d59vp                   1/1     Running   0          35m
kubeapps-internal-kubeops-5b44cc69c6-dbxc7                   1/1     Running   0          35m
kubeapps-postgresql-primary-0                                1/1     Running   0          23m
kubeapps-postgresql-read-0                                   1/1     Running   0          35m

 **kubectl get svc -n webapps**
NAME                             TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                       AGE
kafka-test                       ClusterIP   192.168.81.97     <none>        9092/TCP,5555/TCP             34h
kafka-test-exporter              ClusterIP   192.168.78.80     <none>        9308/TCP                      34h
kafka-test-headless              ClusterIP   None              <none>        9092/TCP                      34h
kafka-test-zookeeper             ClusterIP   192.168.99.191    <none>        2181/TCP                      34h
kafka-test-zookeeper-headless    ClusterIP   None              <none>        2181/TCP,3888/TCP,2888/TCP    34h
kubeapps                         ClusterIP   192.168.73.155    <none>        80/TCP                        36m
kubeapps-internal-assetsvc       ClusterIP   192.168.80.142    <none>        8080/TCP                      36m
**kubeapps-internal-dashboard      NodePort    192.168.114.245   <none>        8080:30380/TCP                36m**
kubeapps-internal-kubeops        ClusterIP   192.168.113.169   <none>        8080/TCP                      36m
kubeapps-postgresql              ClusterIP   192.168.110.16    <none>        5432/TCP                      36m
kubeapps-postgresql-headless     ClusterIP   None              <none>        5432/TCP                      36m
kubeapps-postgresql-read         ClusterIP   192.168.100.238   <none>        5432/TCP                      36m

 **telnet 92.168.114.245  8080**
Trying 92.168.114.245...

telnet failed,so i see postgresql logs
**kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps**
![image](https://user-images.githubusercontent.com/5228314/100358113-a6cdca00-3030-11eb-8569-2e0b736448df.png)

**Comment by antgamdia** [comment] 2020-11-26 14:39
Perhaps it is a problem related to the process of fetching a new chart repository. 
What are the values you're passing through the `values.yaml` file?   Specifically, I'm wondering about the `initialRepos:` you're ussing.

**Comment by absoludity** [comment] 2020-11-26 21:59
The error reads as though the database schema doesn't have the files table (ie. it looks like the same error I'd expect if I manually dropped the files table). Interested to know if this is directly after a new installation of Kubeapps (and if so, is it reproducible), or an upgrade of Kubeapps (and also whether it's reproducible). Thanks.

**Comment by chinaboy007** [comment] 2020-11-27 02:05
> new installation

 this is a new installation

**Comment by chinaboy007** [comment] 2020-11-27 02:08
> Perhaps it is a problem related to the process of fetching a new chart repository.
> What are the values you're passing through the `values.yaml` file? Specifically, I'm wondering about the `initialRepos:` you're using.


I don't change values.yaml  , use commnd   helm install kubeapps . -f values.yaml -n webapps   to  install kubeapps

![image](https://user-images.githubusercontent.com/5228314/100402881-5c803380-3098-11eb-9552-88b4172ca630.png)

**Comment by antgamdia** [comment] 2020-11-27 08:03
When you mentioned:
> telnet failed,so i see postgresql logs 
kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps

You mean `kubectl logs -f kubeapps-postgresql-primary-0` **-n webapps**, don't you?


I have just tried to replicate it but didn't succeed. Below my steps:

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami # if the repo was not installed
helm repo update # just to ensure everything is up to date
helm pull bitnami/kubeapps --untar  # download the latest release locally
cd kubeapps 
helm install kubeapps . -f values.yaml -n webapps --create-namespace  # install kubeapps with the default values
# wait a while...
kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps
```

At the very beginning of the log I do find a trace `ERROR:  relation "repos" does not exist at character 22`, but it is just due to the job was not yet completed by the time Postgresql started.

Perhaps there is a problem during the execution of the jobs. They are responsible for syncing each repo and storing all the information into the PostgreSQL DB.

What is your output of `kubectl get jobs -n webapps` and `kubectl get pods -n webapps` ? 

You can also get useful information by inspecting the logs from the job's pod:
`kubectl logs apprepo-webapps-sync-bitnami-xxxxxxxxxxxxxx  -n webapps`

**Comment by chinaboy007** [comment] 2020-11-27 08:58
> When you mentioned:
> 
> > telnet failed,so i see postgresql logs
> > kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps
> 
> You mean `kubectl logs -f kubeapps-postgresql-primary-0` **-n webapps**, don't you?
> 
> I have just tried to replicate it but didn't succeed. Below my steps:
> 
> ```shell
> helm repo add bitnami https://charts.bitnami.com/bitnami # if the repo was not installed
> helm repo update # just to ensure everything is up to date
> helm pull bitnami/kubeapps --untar  # download the latest release locally
> cd kubeapps 
> helm install kubeapps . -f values.yaml -n webapps --create-namespace  # install kubeapps with the default values
> # wait a while...
> kubectl logs -f kubeapps-postgresql-primary-0 -n kubeapps
> ```
> 
> At the very beginning of the log I do find a trace `ERROR: relation "repos" does not exist at character 22`, but it is just due to the job was not yet completed by the time Postgresql started.
> 
> Perhaps there is a problem during the execution of the jobs. They are responsible for syncing each repo and storing all the information into the PostgreSQL DB.
> 
> What is your output of `kubectl get jobs -n webapps` and `kubectl get pods -n webapps` ?
> 
> You can also get useful information by inspecting the logs from the job's pod:
> `kubectl logs apprepo-webapps-sync-bitnami-xxxxxxxxxxxxxx -n webapps`

![image](https://user-images.githubusercontent.com/5228314/100426516-f1505480-30cb-11eb-95bf-4895823ca615.png)
![image](https://user-images.githubusercontent.com/5228314/100426971-b4389200-30cc-11eb-837a-1112e2e9f004.png)
![image](https://user-images.githubusercontent.com/5228314/100427039-cdd9d980-30cc-11eb-9e88-06885bfc3b4d.png)
![image](https://user-images.githubusercontent.com/5228314/100427150-fc57b480-30cc-11eb-8265-b89ee3547d0b.png)

![image](https://user-images.githubusercontent.com/5228314/100427352-48a2f480-30cd-11eb-92d3-595f8592cd8e.png)
![image](https://user-images.githubusercontent.com/5228314/100427377-5193c600-30cd-11eb-858f-2c85653482a9.png)
![image](https://user-images.githubusercontent.com/5228314/100427449-6a9c7700-30cd-11eb-8f3c-f9883af26f09.png)
![image](https://user-images.githubusercontent.com/5228314/100427501-8142ce00-30cd-11eb-88fd-01cfcac68bdd.png)

I can't login 
![image](https://user-images.githubusercontent.com/5228314/100428394-db905e80-30ce-11eb-95c8-d9fd70d7a4ce.png)
![image](https://user-images.githubusercontent.com/5228314/100428544-0d092a00-30cf-11eb-9dbe-1d08e756a89d.png)

**Comment by antgamdia** [comment] 2020-11-28 12:32
It seems all the assets have been loaded  (I see some network timeouts, but they shouldn't be preventing you to log in).

Could you please attach another screenshot with the chrome developer console open. I'd like to see what happening there with the http requests. 

How are you try to login? Are you generating a token as explained at the [getting started](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md)?

**Comment by andresmgot** [comment] 2020-11-30 08:50
@chinaboy007 the problem is that you are trying to access the service `kubeapps-internal-dashboard` rather than the one called `kubeapps`. If you access that one instead you should be able to login in the application.

**Comment by chinaboy007** [comment] 2020-12-02 07:59
> @ chinaboy007问题是您正在尝试访问该服务，`kubeapps-internal-dashboard`而不是被称为的服务`kubeapps`。如果访问该目录，则应该可以登录该应用程序。

kubectl create serviceaccount kubeapps-operator -n webapps 
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=webapps:kubeapps-operator

![image](https://user-images.githubusercontent.com/5228314/100844824-51be0800-34b7-11eb-8d32-1f3cf1fd9827.png)

this is ok, thank you.

**Comment by antgamdia** [comment] 2020-12-02 08:04
Great! Note this configuration (grating a `clusterrole=clusteradmin` to this `serviceaccount`) is solely intended for demo purposes. Any production-ready environment should configure a more fine-grained set of permissions.

Here you can find a [little FAQ](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/README.md#faq) to help you during this process.

I'm closing this issue, if you need more assistance, feel free to open a new one :)

**Closed by antgamdia** 2020-12-02 08:04 UTC
