### ISSUE TITLE
pq: relation "charts" does not exist. 

### ISSUE THREAD

**Issue by scorpius81** [kubeapps/kubeapps#3818] opened 2021-11-25 07:56 UTC
### Description:
Hi i have install Kubeapps using this command:

helm install kubeapps bitnami/kubeapps \
  --namespace kubeapps \
  --set ingress.enabled=true \
  --set ingress.hostname=k8s-kubeapps.xxxx.xx \
  --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx # or your preferred ingress controller

When log in into Dashboard i see this error:

In App page:
Unable to list apps: Invalid GetInstalledPackageSummaries response from the plugin helm.packages: rpc error: code = Internal desc = Error while fetching related charts: pq: relation "charts" does not exist

In Catalog page:
An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin helm.packages: rpc error: code = Internal desc = Unable to fetch chart categories: pq: relation "charts" does not exist. 

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART          	APP VERSION
kubeapps	kubeapps 	1       	2021-11-24 17:11:47.71564757 +0000 UTC	deployed	kubeapps-7.5.10	2.4.1      
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by absoludity** [comment] 2021-11-25 22:57
Thanks for the report @scorpius81 . Looking at the code, we initialise the tables in the Postgresql DB (with a `CREATE TABLE IF NOT EXISTS`) during every sync of a repository.

And there should be a sync of a repository as part of the installation (as the bitnami repository is added and a sync is done directly).

So I'm wondering if either:

- The app repository controller was not running correctly to pick up the bitnami repo and trigger a sync job, or
- The issue is only temporary until the cluster caught up and the app repo controller generated the sync job (unlikely, as I'd expect this to be very fast).

To find out, can you please:

- First verify that the issue still exists on your deployment, then
- paste the output of `kubectl get pods -n kubeapps`
- If you see a pod there such as `apprepo-kubeapps-sync-bitnami-....`, please paste the logs of that pod as well.

Thanks!

Can you check if this issue persists or it is only seen

**Comment by scorpius81** [comment] 2021-11-26 12:55
kubectl get pods -n kubeapps

NAME                                                         READY   STATUS    RESTARTS   AGE
kubeapps-6464575dbb-54drv                                    1/1     Running   0          41h
kubeapps-6464575dbb-x549j                                    1/1     Running   0          41h
kubeapps-internal-apprepository-controller-c4759f85b-6mkzk   1/1     Running   0          41h
kubeapps-internal-assetsvc-6bcb5d6ff6-57vmt                  1/1     Running   0          41h
kubeapps-internal-dashboard-6854dd7987-dlbbz                 1/1     Running   0          41h
kubeapps-internal-dashboard-6854dd7987-fs2tt                 1/1     Running   0          41h
kubeapps-internal-kubeappsapis-5d965d889b-2zxjj              1/1     Running   0          41h
kubeapps-internal-kubeops-7dc596946c-nt9tm                   1/1     Running   0          41h
kubeapps-internal-kubeops-7dc596946c-plj96                   1/1     Running   0          41h
kubeapps-postgresql-primary-0                                1/1     Running   0          41h
kubeapps-postgresql-read-0                                   1/1     Running   0          41h

Thanks to the explanations I was able to solve my problem:

kubectl get CronJob -n kubeapps  
NAME                            SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
apprepo-kubeapps-sync-bitnami   */10 * * * *   False     0        <none>          43h

I saw that the cronjob had never been run, i have create YAML:


apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2021-11-24T15:41:00Z"
  generation: 1
  labels:
    apprepositories.kubeapps.com/repo-name: bitnami
    apprepositories.kubeapps.com/repo-namespace: kubeapps
  name: apprepo-kubeapps-sync-bitnami
  namespace: kubeapps
  ownerReferences:
  - apiVersion: kubeapps.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppRepository
    name: bitnami
    uid: bc91aab2-9572-4b54-befa-2dd2547f3996
  resourceVersion: "97620472"
  uid: af1031d8-61d3-4f5e-beaa-f97ad6b1623f
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            apprepositories.kubeapps.com/repo-name: bitnami
            apprepositories.kubeapps.com/repo-namespace: kubeapps
        spec:
          containers:
          - args:
            - sync
            - --database-url=kubeapps-postgresql:5432
            - --database-user=postgres
            - --database-name=assets
            - --user-agent-comment=kubeapps/2.4.1
            - --namespace=kubeapps
            - bitnami
            - https://charts.bitnami.com/bitnami
            - helm
            command:
            - /asset-syncer
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: kubeapps-postgresql
            image: docker.io/bitnami/kubeapps-asset-syncer:2.4.1-scratch-r0
            imagePullPolicy: IfNotPresent
            name: sync
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 1001
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 3600
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}

After i have delete cronjob, and and soon after it was recreated 

apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2021-11-26T11:21:42Z"
  labels:
    apprepositories.kubeapps.com/repo-name: bitnami
    apprepositories.kubeapps.com/repo-namespace: kubeapps
  name: apprepo-kubeapps-sync-bitnami
  namespace: kubeapps
  ownerReferences:
  - apiVersion: kubeapps.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppRepository
    name: bitnami
    uid: 03400ae1-2afa-427d-bd1f-3f60ea438329
  resourceVersion: "98110431"
  uid: c088d134-efd4-47a0-b88b-c0d498b7de0b
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            apprepositories.kubeapps.com/repo-name: bitnami
            apprepositories.kubeapps.com/repo-namespace: kubeapps
        spec:
          containers:
          - args:
            - sync
            - --database-url=kubeapps-postgresql:5432
            - --database-user=postgres
            - --database-name=assets
            - --user-agent-comment=kubeapps/2.4.1
            - --namespace=kubeapps
            - bitnami
            - https://charts.bitnami.com/bitnami
            - helm
            command:
            - /asset-syncer
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: kubeapps-postgresql
            image: docker.io/bitnami/kubeapps-asset-syncer:2.4.1-scratch-r0
            imagePullPolicy: IfNotPresent
            name: sync
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 1001
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 3600
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}

I noticed that apiVersion has changed

**Comment by absoludity** [comment] 2021-11-28 23:37
Thanks @scorpius81 , but it's not clear to me what the issue was? I understand that the pods had never been created because the cronjob had never been executed but don't understand why? And this comment:

> I noticed that apiVersion has changed

confuses me too (because we did change the `apiVersion` recently, but only in our unreleased development version, but from your paste above you seem to be using the released chart version.

**Comment by bruj0** [comment] 2021-12-30 17:36
This happend to me, the problem seems to be some kind of failled escaping on the URL.
Because if I run:
```
$ kubectl logs apprepo-kubeapps-sync-bitnami-27348090-vjzml
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp XXX.76.28.177:443: connect: connection refused
Usage:
  asset-syncer sync [REPO NAME] [REPO URL] [REPO TYPE] [flags]
```
The XXX IP is the wildcard to the default domain for the dns lookup so I think the entire URL is being treated as a hostname isntead.

**Comment by absoludity** [comment] 2022-01-04 03:29
> EDIT: I found the problem, when setting "search" in /etc/resolv.conf it breaks DNS resolution for most go applications: [k3s-io/k3s#2801](https://github.com/k3s-io/k3s/issues/2801)

Thanks for the extra information. I'm assuming you resolved the issue by removing the search in your resolv.conf? (Let me know if I'm mistaken - marking closed as not something Kubeapps can fix).

**Closed by absoludity** 2022-01-04 03:29 UTC
Labels: component/asset-syncer
