### ISSUE TITLE
Helm: Make CRDs optional 

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1466] opened 2020-01-17 10:33 UTC
### Description:

Make it optional (but default on) to install the CRDs when doing helm install.
The reason for this is to be able to do two kubeapps installs - one for testing, and proper.

### Steps to reproduce the issue:

1. install kubeapps proper install into ns1
2. install kubeapps test install into ns2, disable crd installs

### Describe the results you received:

Be able to run two kubeapps installs

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by andresmgot** [comment] 2020-01-17 13:47
This should be already supported (I have two kubeapps installations in my cluster without any issue). We are using the CRD folder in our chart that allows you to do that:
https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

Are you getting an error when you try to install two instances of kubeapps?

**Comment by andresmgot** [comment] 2020-01-20 12:40
Hi @davidkarlsen, I am closing this issue because I am not able to reproduce it but please reopen it if you are still hitting the issue. It may be related to using an old version of Helm so make sure you are using a recent version.

**Closed by andresmgot** 2020-01-20 12:40 UTC
