### ISSUE TITLE
can't verify Kubernetes version

### ISSUE THREAD

**Issue by tan-chao** [kubeapps/kubeapps#231] opened 2018-04-08 07:44 UTC
`$ kubeapps up
ERRO[0000] can't verify Kubernetes version: strconv.Atoi: parsing "": invalid syntax`

`kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`

Is the Kubernetes version too late?

**Comment by arapulido** [comment] 2018-04-09 09:09
@tan-chao This is a duplicate of issue https://github.com/kubeapps/kubeapps/issues/114

Are you using minikube? A workaround if you do is to use version 1.8 for now, until we fix the issue

**Closed by arapulido** 2018-04-09 09:09 UTC

**Comment by tan-chao** [comment] 2018-04-10 06:46
@arapulido Yes, I'm using minikube.Thanks for your reply.
